import type { ModuleConfig, SelectOption } from "./types";
import { SECTIONS } from "./sections";
import { childSection } from "./operationsSections";

const ACTIVE: SelectOption[] = [
  { value: "1", label: "Active" },
  { value: "0", label: "Inactive" },
];

const INVENTORY = {
  view: "inventory.view",
  create: "inventory.create",
  edit: "inventory.edit",
  delete: "inventory.delete",
};

const LIBRARY = {
  view: "library.view",
  create: "library.create",
  edit: "library.edit",
  delete: "library.delete",
};

const LAB = {
  view: "lab.view",
  create: "lab.create",
  edit: "lab.edit",
  delete: "lab.delete",
};

const TRANSPORT = {
  view: "transport.view",
  create: "transport.create",
  edit: "transport.edit",
  delete: "transport.delete",
};

const HOSTEL = {
  view: "hostel.view",
  create: "hostel.create",
  edit: "hostel.edit",
  delete: "hostel.delete",
};

const CANTEEN = {
  view: "canteen.view",
  create: "canteen.create",
  edit: "canteen.edit",
  delete: "canteen.delete",
};

const SPORTS = {
  view: "sports.view",
  create: "sports.create",
  edit: "sports.edit",
  delete: "sports.delete",
};

const AFFAIRS = {
  view: "student_affairs.view",
  create: "student_affairs.create",
  edit: "student_affairs.edit",
  delete: "student_affairs.delete",
};

const CIRCULAR = {
  view: "circular.view",
  create: "circular.create",
  edit: "circular.edit",
  delete: "circular.delete",
};

export const OPERATIONS_MODULES: ModuleConfig[] = [
  {
    key: "inventory-categories",
    section: SECTIONS.operations,
    label: "Inventory categories",
    endpoint: "/v1/inventory/categories",
    permissions: INVENTORY,
    searchable: true,
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "description", label: "Description" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  {
    key: "inventory-items",
    section: SECTIONS.operations,
    label: "Inventory items",
    endpoint: "/v1/inventory/items",
    permissions: INVENTORY,
    searchable: true,
    detailSections: [
      childSection({ endpoint: "/v1/inventory/items", title: "Movements", path: "/movements" }),
    ],
    filters: [
      { param: "is_active", label: "Status", options: ACTIVE },
      { param: "low_stock", label: "Low stock", options: [{ value: "1", label: "Low stock only" }] },
    ],
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "inventory_category.name", label: "Category" },
      { key: "quantity", label: "Qty", format: "number", align: "right" },
      { key: "reorder_level", label: "Reorder", format: "number", align: "right" },
      { key: "unit_cost", label: "Unit cost", format: "money", align: "right" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text", required: true },
      {
        name: "inventory_category_id",
        label: "Category",
        type: "lookup",
        lookup: "inventoryCategories",
        displayKey: "inventory_category.name",
      },
      { name: "unit", label: "Unit", type: "text" },
      { name: "unit_cost", label: "Unit cost", type: "number", min: 0 },
      { name: "quantity", label: "Quantity", type: "number" },
      { name: "reorder_level", label: "Reorder level", type: "number", min: 0 },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
    actions: [
      {
        label: "Record movement",
        method: "POST",
        path: (item) => `/v1/inventory/items/${item.id}/movements`,
        permission: "inventory.edit",
        submitLabel: "Save movement",
        successMessage: "Movement recorded.",
        fields: [
          {
            name: "type",
            label: "Type",
            type: "select",
            required: true,
            options: [
              { value: "purchase", label: "Purchase" },
              { value: "issue", label: "Issue" },
              { value: "return", label: "Return" },
              { value: "adjustment", label: "Adjustment" },
              { value: "wastage", label: "Wastage" },
            ],
          },
          { name: "quantity", label: "Quantity", type: "number", required: true },
          { name: "unit_cost", label: "Unit cost", type: "number", min: 0 },
          { name: "moved_on", label: "Date", type: "date" },
          { name: "reference", label: "Reference", type: "text" },
          { name: "notes", label: "Notes", type: "textarea" },
        ],
      },
    ],
  },
  {
    key: "library-books",
    section: SECTIONS.operations,
    label: "Library books",
    endpoint: "/v1/library/books",
    permissions: LIBRARY,
    searchable: true,
    filters: [{ param: "is_active", label: "Status", options: ACTIVE }],
    columns: [
      { key: "title", label: "Title" },
      { key: "author", label: "Author" },
      { key: "isbn", label: "ISBN" },
      { key: "category", label: "Category" },
      { key: "total_copies", label: "Copies", format: "number", align: "right" },
      { key: "available_copies", label: "Available", format: "number", align: "right" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "author", label: "Author", type: "text" },
      { name: "isbn", label: "ISBN", type: "text" },
      { name: "publisher", label: "Publisher", type: "text" },
      { name: "category", label: "Category", type: "text" },
      { name: "total_copies", label: "Total copies", type: "number", min: 1 },
      { name: "available_copies", label: "Available copies", type: "number", min: 0 },
      { name: "shelf", label: "Shelf", type: "text" },
      { name: "price", label: "Price", type: "number", min: 0 },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "library-issues",
    section: SECTIONS.operations,
    label: "Library issues",
    endpoint: "/v1/library/issues",
    permissions: LIBRARY,
    searchable: true,
    filters: [
      { param: "member_type", label: "Member", options: [
        { value: "student", label: "Student" },
        { value: "staff", label: "Staff" },
      ] },
      { param: "status", label: "Status", options: [
        { value: "issued", label: "Issued" },
        { value: "returned", label: "Returned" },
        { value: "overdue", label: "Overdue" },
      ] },
    ],
    columns: [
      { key: "book.title", label: "Book" },
      { key: "member_type", label: "Member type", format: "badge" },
      { key: "student.full_name", label: "Student" },
      { key: "user.name", label: "Staff" },
      { key: "issued_on", label: "Issued", format: "date" },
      { key: "due_on", label: "Due", format: "date" },
      { key: "returned_on", label: "Returned", format: "date" },
    ],
    fields: [
      { name: "book_id", label: "Book", type: "lookup", lookup: "books", required: true, displayKey: "book.title" },
      {
        name: "member_type",
        label: "Member type",
        type: "select",
        options: [
          { value: "student", label: "Student" },
          { value: "staff", label: "Staff" },
        ],
      },
      { name: "student_id", label: "Student", type: "lookup", lookup: "students", displayKey: "student.full_name" },
      { name: "user_id", label: "Staff", type: "lookup", lookup: "staffUsers", displayKey: "user.name" },
      { name: "issued_on", label: "Issued on", type: "date" },
      { name: "due_on", label: "Due on", type: "date" },
      { name: "loan_days", label: "Loan days", type: "number", min: 1, max: 365 },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    actions: [
      {
        label: "Return",
        method: "POST",
        path: (item) => `/v1/library/issues/${item.id}/return`,
        permission: "library.edit",
        confirm: "Mark this book as returned?",
        submitLabel: "Return",
        successMessage: "Book returned.",
        fields: [
          { name: "returned_on", label: "Returned on", type: "date" },
          { name: "lost", label: "Lost", type: "checkbox" },
          { name: "fine_amount", label: "Fine amount", type: "number", min: 0 },
          { name: "notes", label: "Notes", type: "textarea" },
        ],
      },
    ],
  },
  {
    key: "labs",
    section: SECTIONS.operations,
    label: "Labs",
    endpoint: "/v1/labs",
    permissions: LAB,
    searchable: true,
    detailSections: [
      childSection({ endpoint: "/v1/labs", title: "Equipment", path: "/equipment" }),
    ],
    filters: [
      { param: "type", label: "Type", options: [
        { value: "science", label: "Science" },
        { value: "computer", label: "Computer" },
        { value: "language", label: "Language" },
        { value: "other", label: "Other" },
      ] },
      { param: "is_active", label: "Status", options: ACTIVE },
    ],
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "type", label: "Type", format: "badge" },
      { key: "location", label: "Location" },
      { key: "capacity", label: "Capacity", format: "number", align: "right" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text", required: true },
      {
        name: "type",
        label: "Type",
        type: "select",
        options: [
          { value: "science", label: "Science" },
          { value: "computer", label: "Computer" },
          { value: "language", label: "Language" },
          { value: "other", label: "Other" },
        ],
      },
      { name: "location", label: "Location", type: "text" },
      { name: "capacity", label: "Capacity", type: "number", min: 0 },
      { name: "incharge_user_id", label: "Incharge", type: "lookup", lookup: "staffUsers", displayKey: "incharge.name" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "lab-bookings",
    section: SECTIONS.operations,
    label: "Lab bookings",
    endpoint: "/v1/lab-bookings",
    permissions: LAB,
    filters: [
      { param: "status", label: "Status", options: [
        { value: "scheduled", label: "Scheduled" },
        { value: "completed", label: "Completed" },
        { value: "cancelled", label: "Cancelled" },
      ] },
    ],
    columns: [
      { key: "lab.name", label: "Lab" },
      { key: "class_room.name", label: "Class" },
      { key: "teacher.name", label: "Teacher" },
      { key: "session_date", label: "Date", format: "date" },
      { key: "start_time", label: "Start" },
      { key: "end_time", label: "End" },
      { key: "status", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "lab_id", label: "Lab", type: "lookup", lookup: "labs", required: true, displayKey: "lab.name" },
      { name: "class_room_id", label: "Class", type: "lookup", lookup: "classRooms", displayKey: "class_room.name" },
      { name: "teacher_user_id", label: "Teacher", type: "lookup", lookup: "staffUsers", displayKey: "teacher.name" },
      { name: "session_date", label: "Session date", type: "date", required: true },
      { name: "start_time", label: "Start time", type: "time", required: true },
      { name: "end_time", label: "End time", type: "time", required: true },
      { name: "purpose", label: "Purpose", type: "text" },
      { name: "status", label: "Status", type: "select", options: [
        { value: "scheduled", label: "Scheduled" },
        { value: "completed", label: "Completed" },
        { value: "cancelled", label: "Cancelled" },
      ] },
    ],
    actions: [
      {
        label: "Complete",
        method: "POST",
        path: (item) => `/v1/lab-bookings/${item.id}/complete`,
        permission: "lab.edit",
        confirm: "Mark this booking as completed?",
        submitLabel: "Complete",
        successMessage: "Booking completed.",
      },
      {
        label: "Cancel",
        method: "POST",
        path: (item) => `/v1/lab-bookings/${item.id}/cancel`,
        permission: "lab.edit",
        confirm: "Cancel this booking?",
        submitLabel: "Cancel",
        successMessage: "Booking cancelled.",
      },
    ],
  },
  {
    key: "transport-vehicles",
    section: SECTIONS.operations,
    label: "Vehicles",
    endpoint: "/v1/transport/vehicles",
    permissions: TRANSPORT,
    searchable: true,
    filters: [
      { param: "type", label: "Type", options: [
        { value: "bus", label: "Bus" },
        { value: "van", label: "Van" },
        { value: "coaster", label: "Coaster" },
        { value: "car", label: "Car" },
      ] },
      { param: "is_active", label: "Status", options: ACTIVE },
    ],
    columns: [
      { key: "name", label: "Name" },
      { key: "registration_no", label: "Registration" },
      { key: "type", label: "Type", format: "badge" },
      { key: "capacity", label: "Capacity", format: "number", align: "right" },
      { key: "driver_name", label: "Driver" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "registration_no", label: "Registration no", type: "text", required: true },
      { name: "type", label: "Type", type: "select", options: [
        { value: "bus", label: "Bus" },
        { value: "van", label: "Van" },
        { value: "coaster", label: "Coaster" },
        { value: "car", label: "Car" },
      ] },
      { name: "capacity", label: "Capacity", type: "number", min: 0 },
      { name: "model", label: "Model", type: "text" },
      { name: "driver_user_id", label: "Driver user", type: "lookup", lookup: "staffUsers", displayKey: "driver.name" },
      { name: "driver_name", label: "Driver name", type: "text" },
      { name: "driver_phone", label: "Driver phone", type: "text" },
      { name: "conductor_name", label: "Conductor", type: "text" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "transport-routes",
    section: SECTIONS.operations,
    label: "Transport routes",
    endpoint: "/v1/transport/routes",
    permissions: TRANSPORT,
    searchable: true,
    detailSections: [
      childSection({ endpoint: "/v1/transport/routes", title: "Stops", path: "/stops" }),
    ],
    filters: [{ param: "is_active", label: "Status", options: ACTIVE }],
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "start_point", label: "From" },
      { key: "end_point", label: "To" },
      { key: "distance_km", label: "Distance", format: "number", align: "right" },
      { key: "fare", label: "Fare", format: "money", align: "right" },
      { key: "vehicle.name", label: "Vehicle" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text", required: true },
      { name: "start_point", label: "Start point", type: "text" },
      { name: "end_point", label: "End point", type: "text" },
      { name: "distance_km", label: "Distance (km)", type: "number", min: 0 },
      { name: "fare", label: "Fare", type: "number", min: 0 },
      { name: "vehicle_id", label: "Vehicle", type: "lookup", lookup: "vehicles", displayKey: "vehicle.name" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "transport-allocations",
    section: SECTIONS.operations,
    label: "Transport allocations",
    endpoint: "/v1/transport/allocations",
    permissions: TRANSPORT,
    filters: [
      { param: "direction", label: "Direction", options: [
        { value: "pickup", label: "Pickup" },
        { value: "drop", label: "Drop" },
        { value: "both", label: "Both" },
      ] },
    ],
    columns: [
      { key: "student.full_name", label: "Student" },
      { key: "route.name", label: "Route" },
      { key: "vehicle.name", label: "Vehicle" },
      { key: "direction", label: "Direction", format: "badge" },
      { key: "fare", label: "Fare", format: "money", align: "right" },
      { key: "start_date", label: "From", format: "date" },
      { key: "end_date", label: "To", format: "date" },
    ],
    fields: [
      { name: "student_id", label: "Student", type: "lookup", lookup: "students", required: true, displayKey: "student.full_name" },
      { name: "transport_route_id", label: "Route", type: "lookup", lookup: "transportRoutes", required: true, displayKey: "route.name" },
      { name: "vehicle_id", label: "Vehicle", type: "lookup", lookup: "vehicles", displayKey: "vehicle.name" },
      { name: "transport_route_stop_id", label: "Stop ID", type: "number" },
      { name: "direction", label: "Direction", type: "select", options: [
        { value: "pickup", label: "Pickup" },
        { value: "drop", label: "Drop" },
        { value: "both", label: "Both" },
      ] },
      { name: "start_date", label: "Start date", type: "date" },
      { name: "end_date", label: "End date", type: "date" },
      { name: "fare", label: "Fare", type: "number", min: 0 },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    actions: [
      {
        label: "Deallocate",
        method: "POST",
        path: (item) => `/v1/transport/allocations/${item.id}/deallocate`,
        permission: "transport.edit",
        confirm: "End this transport allocation?",
        submitLabel: "Deallocate",
        successMessage: "Allocation ended.",
        fields: [{ name: "end_date", label: "End date", type: "date" }],
      },
    ],
  },
  {
    key: "hostels",
    section: SECTIONS.operations,
    label: "Hostels",
    endpoint: "/v1/hostels",
    permissions: HOSTEL,
    searchable: true,
    detailSections: [
      childSection({ endpoint: "/v1/hostels", title: "Rooms", path: "/rooms" }),
    ],
    filters: [
      { param: "type", label: "Type", options: [
        { value: "boys", label: "Boys" },
        { value: "girls", label: "Girls" },
        { value: "mixed", label: "Mixed" },
      ] },
      { param: "is_active", label: "Status", options: ACTIVE },
    ],
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "type", label: "Type", format: "badge" },
      { key: "warden_name", label: "Warden" },
      { key: "capacity", label: "Capacity", format: "number", align: "right" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text", required: true },
      { name: "type", label: "Type", type: "select", options: [
        { value: "boys", label: "Boys" },
        { value: "girls", label: "Girls" },
        { value: "mixed", label: "Mixed" },
      ] },
      { name: "warden_user_id", label: "Warden user", type: "lookup", lookup: "staffUsers", displayKey: "warden.name" },
      { name: "warden_name", label: "Warden name", type: "text" },
      { name: "warden_phone", label: "Warden phone", type: "text" },
      { name: "address", label: "Address", type: "text" },
      { name: "capacity", label: "Capacity", type: "number", min: 0 },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "hostel-allocations",
    section: SECTIONS.operations,
    label: "Hostel allocations",
    endpoint: "/v1/hostel-allocations",
    permissions: HOSTEL,
    columns: [
      { key: "student.full_name", label: "Student" },
      { key: "room.name", label: "Room" },
      { key: "bed_no", label: "Bed" },
      { key: "allocated_on", label: "Allocated", format: "date" },
      { key: "monthly_fee", label: "Monthly fee", format: "money", align: "right" },
      { key: "vacated_on", label: "Vacated", format: "date" },
    ],
    fields: [
      { name: "hostel_room_id", label: "Room ID", type: "number", required: true },
      { name: "student_id", label: "Student", type: "lookup", lookup: "students", required: true, displayKey: "student.full_name" },
      { name: "bed_no", label: "Bed no", type: "text" },
      { name: "allocated_on", label: "Allocated on", type: "date" },
      { name: "monthly_fee", label: "Monthly fee", type: "number", min: 0 },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    actions: [
      {
        label: "Vacate",
        method: "POST",
        path: (item) => `/v1/hostel-allocations/${item.id}/vacate`,
        permission: "hostel.edit",
        confirm: "Vacate this allocation?",
        submitLabel: "Vacate",
        successMessage: "Allocation vacated.",
        fields: [{ name: "vacated_on", label: "Vacated on", type: "date" }],
      },
    ],
  },
  {
    key: "hostel-outpasses",
    section: SECTIONS.operations,
    label: "Hostel outpasses",
    endpoint: "/v1/hostel-outpasses",
    permissions: HOSTEL,
    filters: [{ param: "status", label: "Status", options: [
      { value: "pending", label: "Pending" },
      { value: "approved", label: "Approved" },
      { value: "rejected", label: "Rejected" },
      { value: "returned", label: "Returned" },
    ] }],
    columns: [
      { key: "student.full_name", label: "Student" },
      { key: "from_datetime", label: "From", format: "date" },
      { key: "to_datetime", label: "To", format: "date" },
      { key: "reason", label: "Reason" },
      { key: "status", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "hostel_allocation_id", label: "Allocation ID", type: "number" },
      { name: "student_id", label: "Student", type: "lookup", lookup: "students", required: true, displayKey: "student.full_name" },
      { name: "from_datetime", label: "From", type: "date", required: true },
      { name: "to_datetime", label: "To", type: "date", required: true },
      { name: "reason", label: "Reason", type: "text", required: true },
    ],
    actions: [
      {
        label: "Approve",
        method: "POST",
        path: (item) => `/v1/hostel-outpasses/${item.id}/approve`,
        permission: "hostel.edit",
        confirm: "Approve this outpass?",
        submitLabel: "Approve",
        successMessage: "Outpass approved.",
      },
      {
        label: "Reject",
        method: "POST",
        path: (item) => `/v1/hostel-outpasses/${item.id}/reject`,
        permission: "hostel.edit",
        confirm: "Reject this outpass?",
        submitLabel: "Reject",
        successMessage: "Outpass rejected.",
      },
      {
        label: "Mark returned",
        method: "POST",
        path: (item) => `/v1/hostel-outpasses/${item.id}/return`,
        permission: "hostel.edit",
        confirm: "Mark this outpass as returned?",
        submitLabel: "Mark returned",
        successMessage: "Outpass returned.",
      },
    ],
  },
  {
    key: "canteen-items",
    section: SECTIONS.operations,
    label: "Canteen items",
    endpoint: "/v1/canteen/items",
    permissions: CANTEEN,
    searchable: true,
    filters: [{ param: "is_active", label: "Status", options: ACTIVE }],
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "category", label: "Category" },
      { key: "price", label: "Price", format: "money", align: "right" },
      { key: "stock_quantity", label: "Stock", format: "number", align: "right" },
      { key: "reorder_level", label: "Reorder", format: "number", align: "right" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text", required: true },
      { name: "category", label: "Category", type: "text" },
      { name: "unit", label: "Unit", type: "text" },
      { name: "price", label: "Price", type: "number", required: true, min: 0 },
      { name: "cost_price", label: "Cost price", type: "number", min: 0 },
      { name: "track_stock", label: "Track stock", type: "checkbox", defaultValue: true },
      { name: "stock_quantity", label: "Stock quantity", type: "number" },
      { name: "reorder_level", label: "Reorder level", type: "number", min: 0 },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
      { name: "description", label: "Description", type: "textarea" },
    ],
    actions: [
      {
        label: "Adjust stock",
        method: "POST",
        path: (item) => `/v1/canteen/items/${item.id}/adjust-stock`,
        permission: "canteen.approve",
        submitLabel: "Adjust",
        successMessage: "Stock adjusted.",
        fields: [
          { name: "quantity", label: "Quantity change", type: "number", required: true },
          { name: "unit_cost", label: "Unit cost", type: "number", min: 0 },
          { name: "notes", label: "Notes", type: "textarea" },
        ],
      },
    ],
  },
  {
    key: "canteen-suppliers",
    section: SECTIONS.operations,
    label: "Canteen suppliers",
    endpoint: "/v1/canteen/suppliers",
    permissions: CANTEEN,
    searchable: true,
    filters: [{ param: "is_active", label: "Status", options: ACTIVE }],
    columns: [
      { key: "name", label: "Name" },
      { key: "contact_person", label: "Contact" },
      { key: "phone", label: "Phone" },
      { key: "email", label: "Email" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "contact_person", label: "Contact person", type: "text" },
      { name: "phone", label: "Phone", type: "text" },
      { name: "email", label: "Email", type: "email" },
      { name: "address", label: "Address", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "canteen-stock-entries",
    section: SECTIONS.operations,
    label: "Canteen stock entries",
    endpoint: "/v1/canteen/stock-entries",
    permissions: CANTEEN,
    filters: [{ param: "type", label: "Type", options: [
      { value: "purchase", label: "Purchase" },
      { value: "adjustment", label: "Adjustment" },
      { value: "wastage", label: "Wastage" },
      { value: "return", label: "Return" },
    ] }],
    columns: [
      { key: "item.name", label: "Item" },
      { key: "type", label: "Type", format: "badge" },
      { key: "quantity", label: "Qty", format: "number", align: "right" },
      { key: "unit_cost", label: "Unit cost", format: "money", align: "right" },
      { key: "entry_date", label: "Date", format: "date" },
      { key: "reference", label: "Reference" },
    ],
    fields: [
      { name: "canteen_item_id", label: "Item", type: "lookup", lookup: "canteenItems", required: true, displayKey: "item.name" },
      { name: "supplier_id", label: "Supplier", type: "lookup", lookup: "canteenSuppliers", displayKey: "supplier.name" },
      { name: "type", label: "Type", type: "select", options: [
        { value: "purchase", label: "Purchase" },
        { value: "adjustment", label: "Adjustment" },
        { value: "wastage", label: "Wastage" },
        { value: "return", label: "Return" },
      ] },
      { name: "quantity", label: "Quantity", type: "number", required: true },
      { name: "unit_cost", label: "Unit cost", type: "number", min: 0 },
      { name: "entry_date", label: "Entry date", type: "date" },
      { name: "reference", label: "Reference", type: "text" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "canteen-sales",
    section: SECTIONS.operations,
    label: "Canteen sales",
    endpoint: "/v1/canteen/sales",
    permissions: CANTEEN,
    filters: [{ param: "payment_method", label: "Payment", options: [
      { value: "cash", label: "Cash" },
      { value: "wallet", label: "Wallet" },
      { value: "credit", label: "Credit" },
    ] }],
    columns: [
      { key: "student.full_name", label: "Student" },
      { key: "customer_name", label: "Customer" },
      { key: "payment_method", label: "Payment", format: "badge" },
      { key: "total", label: "Total", format: "money", align: "right" },
      { key: "sold_on", label: "Sold on", format: "date" },
      { key: "status", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "student_id", label: "Student", type: "lookup", lookup: "students", displayKey: "student.full_name" },
      { name: "customer_name", label: "Customer name", type: "text" },
      { name: "payment_method", label: "Payment method", type: "select", required: true, options: [
        { value: "cash", label: "Cash" },
        { value: "wallet", label: "Wallet" },
        { value: "credit", label: "Credit" },
      ] },
      { name: "discount", label: "Discount", type: "number", min: 0 },
      { name: "sold_on", label: "Sold on", type: "date" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    actions: [
      {
        label: "Void",
        method: "POST",
        path: (item) => `/v1/canteen/sales/${item.id}/void`,
        permission: "canteen.approve",
        confirm: "Void this sale?",
        submitLabel: "Void",
        successMessage: "Sale voided.",
        fields: [{ name: "memo", label: "Memo", type: "textarea" }],
      },
    ],
  },
  {
    key: "canteen-wallets",
    section: SECTIONS.operations,
    label: "Canteen wallets",
    endpoint: "/v1/canteen/wallets",
    permissions: CANTEEN,
    detailSections: [
      childSection({ endpoint: "/v1/canteen/wallets", title: "Transactions", path: "/transactions" }),
    ],
    columns: [
      { key: "student.full_name", label: "Student" },
      { key: "balance", label: "Balance", format: "money", align: "right" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [],
    actions: [
      {
        label: "Top up",
        method: "POST",
        path: (item) => `/v1/canteen/wallets/${item.id}/top-up`,
        permission: "canteen.create",
        submitLabel: "Top up",
        successMessage: "Wallet topped up.",
        fields: [
          { name: "amount", label: "Amount", type: "number", required: true, min: 0 },
          { name: "notes", label: "Notes", type: "textarea" },
        ],
      },
      {
        label: "Adjust",
        method: "POST",
        path: (item) => `/v1/canteen/wallets/${item.id}/adjust`,
        permission: "canteen.approve",
        submitLabel: "Adjust",
        successMessage: "Wallet adjusted.",
        fields: [
          { name: "amount", label: "Amount", type: "number", required: true },
          { name: "notes", label: "Notes", type: "textarea" },
        ],
      },
    ],
  },
  {
    key: "canteen-hygiene",
    section: SECTIONS.operations,
    label: "Canteen hygiene",
    endpoint: "/v1/canteen/hygiene-checks",
    permissions: CANTEEN,
    filters: [{ param: "status", label: "Status", options: [
      { value: "pass", label: "Pass" },
      { value: "needs_attention", label: "Needs attention" },
      { value: "fail", label: "Fail" },
    ] }],
    columns: [
      { key: "check_date", label: "Date", format: "date" },
      { key: "area", label: "Area" },
      { key: "status", label: "Status", format: "badge" },
      { key: "score", label: "Score", format: "number", align: "right" },
      { key: "remarks", label: "Remarks" },
    ],
    fields: [
      { name: "check_date", label: "Check date", type: "date", required: true },
      { name: "area", label: "Area", type: "text", required: true },
      { name: "status", label: "Status", type: "select", options: [
        { value: "pass", label: "Pass" },
        { value: "needs_attention", label: "Needs attention" },
        { value: "fail", label: "Fail" },
      ] },
      { name: "score", label: "Score", type: "number", min: 0, max: 100 },
      { name: "remarks", label: "Remarks", type: "textarea" },
    ],
  },
  {
    key: "sports-catalog",
    section: SECTIONS.operations,
    label: "Sports",
    endpoint: "/v1/sports",
    permissions: SPORTS,
    searchable: true,
    filters: [
      { param: "category", label: "Category", options: [
        { value: "indoor", label: "Indoor" },
        { value: "outdoor", label: "Outdoor" },
        { value: "athletics", label: "Athletics" },
      ] },
      { param: "is_active", label: "Status", options: ACTIVE },
    ],
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "category", label: "Category", format: "badge" },
      { key: "season", label: "Season" },
      { key: "budget", label: "Budget", format: "money", align: "right" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text", required: true },
      { name: "category", label: "Category", type: "select", options: [
        { value: "indoor", label: "Indoor" },
        { value: "outdoor", label: "Outdoor" },
        { value: "athletics", label: "Athletics" },
      ] },
      { name: "season", label: "Season", type: "text" },
      { name: "coach_user_id", label: "Coach", type: "lookup", lookup: "staffUsers", displayKey: "coach.name" },
      { name: "min_age_years", label: "Min age", type: "number", min: 1, max: 100 },
      { name: "max_age_years", label: "Max age", type: "number", min: 1, max: 100 },
      { name: "min_attendance_percent", label: "Min attendance %", type: "number", min: 0, max: 100 },
      { name: "budget", label: "Budget", type: "number", min: 0 },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
      { name: "rules", label: "Rules", type: "textarea" },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  {
    key: "sports-teams",
    section: SECTIONS.operations,
    label: "Sports teams",
    endpoint: "/v1/sports/teams",
    permissions: SPORTS,
    searchable: true,
    detailSections: [
      childSection({ endpoint: "/v1/sports/teams", title: "Members", path: "/members" }),
    ],
    filters: [{ param: "is_active", label: "Status", options: ACTIVE }],
    columns: [
      { key: "name", label: "Name" },
      { key: "sport.name", label: "Sport" },
      { key: "age_group", label: "Age group" },
      { key: "gender", label: "Gender", format: "badge" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "sport_id", label: "Sport", type: "lookup", lookup: "sports", required: true, displayKey: "sport.name" },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "age_group", label: "Age group", type: "text" },
      { name: "gender", label: "Gender", type: "select", options: [
        { value: "male", label: "Male" },
        { value: "female", label: "Female" },
        { value: "mixed", label: "Mixed" },
      ] },
      { name: "coach_user_id", label: "Coach", type: "lookup", lookup: "staffUsers", displayKey: "coach.name" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "sports-equipment",
    section: SECTIONS.operations,
    label: "Sports equipment",
    endpoint: "/v1/sports/equipment",
    permissions: SPORTS,
    searchable: true,
    detailSections: [
      childSection({ endpoint: "/v1/sports/equipment", title: "Movements", path: "/movements" }),
    ],
    filters: [{ param: "condition", label: "Condition", options: [
      { value: "good", label: "Good" },
      { value: "fair", label: "Fair" },
      { value: "damaged", label: "Damaged" },
    ] }],
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "sport.name", label: "Sport" },
      { key: "quantity", label: "Qty", format: "number", align: "right" },
      { key: "available_quantity", label: "Available", format: "number", align: "right" },
      { key: "condition", label: "Condition", format: "badge" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text", required: true },
      { name: "sport_id", label: "Sport", type: "lookup", lookup: "sports", displayKey: "sport.name" },
      { name: "unit", label: "Unit", type: "text" },
      { name: "unit_cost", label: "Unit cost", type: "number", min: 0 },
      { name: "quantity", label: "Quantity", type: "number", min: 0 },
      { name: "available_quantity", label: "Available", type: "number", min: 0 },
      { name: "condition", label: "Condition", type: "select", options: [
        { value: "good", label: "Good" },
        { value: "fair", label: "Fair" },
        { value: "damaged", label: "Damaged" },
      ] },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    actions: [
      {
        label: "Record movement",
        method: "POST",
        path: (item) => `/v1/sports/equipment/${item.id}/movements`,
        permission: "sports.edit",
        submitLabel: "Save movement",
        successMessage: "Movement recorded.",
        fields: [
          { name: "type", label: "Type", type: "select", required: true, options: [
            { value: "purchase", label: "Purchase" },
            { value: "issue", label: "Issue" },
            { value: "return", label: "Return" },
            { value: "adjustment", label: "Adjustment" },
            { value: "damage", label: "Damage" },
          ] },
          { name: "quantity", label: "Quantity", type: "number", required: true },
          { name: "movement_date", label: "Date", type: "date" },
          { name: "remarks", label: "Remarks", type: "textarea" },
        ],
      },
    ],
  },
  {
    key: "sports-fixtures",
    section: SECTIONS.operations,
    label: "Sports fixtures",
    endpoint: "/v1/sports/fixtures",
    permissions: SPORTS,
    filters: [{ param: "status", label: "Status", options: [
      { value: "scheduled", label: "Scheduled" },
      { value: "completed", label: "Completed" },
      { value: "cancelled", label: "Cancelled" },
    ] }],
    columns: [
      { key: "sport.name", label: "Sport" },
      { key: "opponent", label: "Opponent" },
      { key: "home_away", label: "Home/Away", format: "badge" },
      { key: "fixture_date", label: "Date", format: "date" },
      { key: "venue", label: "Venue" },
      { key: "status", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "sport_id", label: "Sport", type: "lookup", lookup: "sports", required: true, displayKey: "sport.name" },
      { name: "sport_team_id", label: "Team", type: "lookup", lookup: "sportTeams", dependsOn: "sport_id", displayKey: "team.name" },
      { name: "opponent", label: "Opponent", type: "text", required: true },
      { name: "home_away", label: "Home/Away", type: "select", options: [
        { value: "home", label: "Home" },
        { value: "away", label: "Away" },
        { value: "neutral", label: "Neutral" },
      ] },
      { name: "venue", label: "Venue", type: "text" },
      { name: "fixture_date", label: "Fixture date", type: "date", required: true },
      { name: "start_time", label: "Start time", type: "time" },
      { name: "status", label: "Status", type: "select", options: [
        { value: "scheduled", label: "Scheduled" },
        { value: "completed", label: "Completed" },
        { value: "cancelled", label: "Cancelled" },
      ] },
      { name: "remarks", label: "Remarks", type: "textarea" },
    ],
    actions: [
      {
        label: "Record result",
        method: "POST",
        path: (item) => `/v1/sports/fixtures/${item.id}/result`,
        permission: "sports.edit",
        submitLabel: "Save result",
        successMessage: "Result recorded.",
        fields: [
          { name: "our_score", label: "Our score", type: "number", required: true, min: 0 },
          { name: "opponent_score", label: "Opponent score", type: "number", required: true, min: 0 },
          { name: "remarks", label: "Remarks", type: "textarea" },
        ],
      },
    ],
  },
  {
    key: "sports-training",
    section: SECTIONS.operations,
    label: "Training sessions",
    endpoint: "/v1/sports/training-sessions",
    permissions: SPORTS,
    columns: [
      { key: "title", label: "Title" },
      { key: "team.name", label: "Team" },
      { key: "session_date", label: "Date", format: "date" },
      { key: "start_time", label: "Start" },
      { key: "end_time", label: "End" },
      { key: "venue", label: "Venue" },
    ],
    fields: [
      { name: "sport_team_id", label: "Team", type: "lookup", lookup: "sportTeams", required: true, displayKey: "team.name" },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "session_date", label: "Date", type: "date", required: true },
      { name: "start_time", label: "Start time", type: "time" },
      { name: "end_time", label: "End time", type: "time" },
      { name: "venue", label: "Venue", type: "text" },
      { name: "focus", label: "Focus", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "sports-achievements",
    section: SECTIONS.operations,
    label: "Sports achievements",
    endpoint: "/v1/sports/achievements",
    permissions: SPORTS,
    filters: [{ param: "level", label: "Level", options: [
      { value: "school", label: "School" },
      { value: "district", label: "District" },
      { value: "state", label: "State" },
      { value: "national", label: "National" },
      { value: "international", label: "International" },
    ] }],
    columns: [
      { key: "title", label: "Title" },
      { key: "sport.name", label: "Sport" },
      { key: "student.full_name", label: "Student" },
      { key: "level", label: "Level", format: "badge" },
      { key: "position", label: "Position" },
      { key: "achieved_on", label: "Date", format: "date" },
    ],
    fields: [
      { name: "sport_id", label: "Sport", type: "lookup", lookup: "sports", required: true, displayKey: "sport.name" },
      { name: "student_id", label: "Student", type: "lookup", lookup: "students", displayKey: "student.full_name" },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "level", label: "Level", type: "select", options: [
        { value: "school", label: "School" },
        { value: "district", label: "District" },
        { value: "state", label: "State" },
        { value: "national", label: "National" },
        { value: "international", label: "International" },
      ] },
      { name: "position", label: "Position", type: "text" },
      { name: "achieved_on", label: "Achieved on", type: "date", required: true },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  {
    key: "sa-clubs",
    section: SECTIONS.operations,
    label: "Clubs",
    endpoint: "/v1/student-affairs/clubs",
    permissions: AFFAIRS,
    searchable: true,
    detailSections: [
      childSection({ endpoint: "/v1/student-affairs/clubs", title: "Members", path: "/members" }),
    ],
    filters: [{ param: "is_active", label: "Status", options: ACTIVE }],
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "category", label: "Category" },
      { key: "patron.name", label: "Patron" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text", required: true },
      { name: "category", label: "Category", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "patron_user_id", label: "Patron", type: "lookup", lookup: "staffUsers", displayKey: "patron.name" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "sa-events",
    section: SECTIONS.operations,
    label: "Events",
    endpoint: "/v1/student-affairs/events",
    permissions: AFFAIRS,
    searchable: true,
    detailSections: [
      childSection({ endpoint: "/v1/student-affairs/events", title: "Participants", path: "/participants" }),
    ],
    filters: [{ param: "status", label: "Status", options: [
      { value: "planned", label: "Planned" },
      { value: "ongoing", label: "Ongoing" },
      { value: "completed", label: "Completed" },
      { value: "cancelled", label: "Cancelled" },
    ] }],
    columns: [
      { key: "title", label: "Title" },
      { key: "type", label: "Type" },
      { key: "starts_on", label: "Starts", format: "date" },
      { key: "ends_on", label: "Ends", format: "date" },
      { key: "venue", label: "Venue" },
      { key: "status", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "type", label: "Type", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "starts_on", label: "Starts on", type: "date", required: true },
      { name: "ends_on", label: "Ends on", type: "date" },
      { name: "venue", label: "Venue", type: "text" },
      { name: "budget", label: "Budget", type: "number", min: 0 },
      { name: "status", label: "Status", type: "select", options: [
        { value: "planned", label: "Planned" },
        { value: "ongoing", label: "Ongoing" },
        { value: "completed", label: "Completed" },
        { value: "cancelled", label: "Cancelled" },
      ] },
    ],
  },
  {
    key: "sa-certificates",
    section: SECTIONS.operations,
    label: "Certificates",
    endpoint: "/v1/student-affairs/certificates",
    permissions: AFFAIRS,
    filters: [{ param: "status", label: "Status", options: [
      { value: "pending", label: "Pending" },
      { value: "issued", label: "Issued" },
      { value: "revoked", label: "Revoked" },
    ] }],
    columns: [
      { key: "student.full_name", label: "Student" },
      { key: "type", label: "Type" },
      { key: "title", label: "Title" },
      { key: "serial_no", label: "Serial" },
      { key: "issued_on", label: "Issued", format: "date" },
      { key: "status", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "student_id", label: "Student", type: "lookup", lookup: "students", required: true, displayKey: "student.full_name" },
      { name: "type", label: "Type", type: "text", required: true },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "serial_no", label: "Serial no", type: "text" },
      { name: "issued_on", label: "Issued on", type: "date" },
      { name: "status", label: "Status", type: "select", options: [
        { value: "pending", label: "Pending" },
        { value: "issued", label: "Issued" },
        { value: "revoked", label: "Revoked" },
      ] },
      { name: "remarks", label: "Remarks", type: "textarea" },
    ],
    actions: [
      {
        label: "Issue",
        method: "POST",
        path: (item) => `/v1/student-affairs/certificates/${item.id}/issue`,
        permission: "student_affairs.approve",
        confirm: "Issue this certificate?",
        submitLabel: "Issue",
        successMessage: "Certificate issued.",
        fields: [
          { name: "serial_no", label: "Serial no", type: "text" },
          { name: "issued_on", label: "Issued on", type: "date" },
        ],
      },
    ],
  },
  {
    key: "sa-welfare",
    section: SECTIONS.operations,
    label: "Welfare records",
    endpoint: "/v1/student-affairs/welfare-records",
    permissions: AFFAIRS,
    filters: [
      { param: "type", label: "Type", options: [
        { value: "health", label: "Health" },
        { value: "medical", label: "Medical" },
        { value: "welfare", label: "Welfare" },
        { value: "incident", label: "Incident" },
      ] },
      { param: "status", label: "Status", options: [
        { value: "open", label: "Open" },
        { value: "monitoring", label: "Monitoring" },
        { value: "closed", label: "Closed" },
      ] },
    ],
    columns: [
      { key: "title", label: "Title" },
      { key: "student.full_name", label: "Student" },
      { key: "type", label: "Type", format: "badge" },
      { key: "recorded_on", label: "Date", format: "date" },
      { key: "status", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "student_id", label: "Student", type: "lookup", lookup: "students", required: true, displayKey: "student.full_name" },
      { name: "type", label: "Type", type: "select", required: true, options: [
        { value: "health", label: "Health" },
        { value: "medical", label: "Medical" },
        { value: "welfare", label: "Welfare" },
        { value: "incident", label: "Incident" },
      ] },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "recorded_on", label: "Recorded on", type: "date", required: true },
      { name: "status", label: "Status", type: "select", options: [
        { value: "open", label: "Open" },
        { value: "monitoring", label: "Monitoring" },
        { value: "closed", label: "Closed" },
      ] },
      { name: "follow_up", label: "Follow up", type: "textarea" },
    ],
  },
  {
    key: "sa-alumni",
    section: SECTIONS.operations,
    label: "Alumni",
    endpoint: "/v1/student-affairs/alumni",
    permissions: AFFAIRS,
    searchable: true,
    columns: [
      { key: "student.full_name", label: "Student" },
      { key: "graduation_year", label: "Graduation year" },
      { key: "current_occupation", label: "Occupation" },
      { key: "employer", label: "Employer" },
      { key: "city", label: "City" },
    ],
    fields: [
      { name: "student_id", label: "Student", type: "lookup", lookup: "students", displayKey: "student.full_name" },
      { name: "graduation_year", label: "Graduation year", type: "text" },
      { name: "current_occupation", label: "Current occupation", type: "text" },
      { name: "employer", label: "Employer", type: "text" },
      { name: "email", label: "Email", type: "email" },
      { name: "phone", label: "Phone", type: "text" },
      { name: "city", label: "City", type: "text" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "sa-council",
    section: SECTIONS.operations,
    label: "Council members",
    endpoint: "/v1/student-affairs/council-members",
    permissions: AFFAIRS,
    filters: [{ param: "is_active", label: "Status", options: ACTIVE }],
    columns: [
      { key: "student.full_name", label: "Student" },
      { key: "position", label: "Position" },
      { key: "term", label: "Term" },
      { key: "from_date", label: "From", format: "date" },
      { key: "to_date", label: "To", format: "date" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "student_id", label: "Student", type: "lookup", lookup: "students", required: true, displayKey: "student.full_name" },
      { name: "position", label: "Position", type: "text", required: true },
      { name: "term", label: "Term", type: "text" },
      { name: "from_date", label: "From date", type: "date" },
      { name: "to_date", label: "To date", type: "date" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "sa-complaints",
    section: SECTIONS.operations,
    label: "Complaints",
    endpoint: "/v1/student-affairs/complaints",
    permissions: AFFAIRS,
    searchable: true,
    filters: [
      { param: "status", label: "Status", options: [
        { value: "open", label: "Open" },
        { value: "in_progress", label: "In progress" },
        { value: "resolved", label: "Resolved" },
        { value: "rejected", label: "Rejected" },
      ] },
      { param: "priority", label: "Priority", options: [
        { value: "low", label: "Low" },
        { value: "medium", label: "Medium" },
        { value: "high", label: "High" },
      ] },
    ],
    columns: [
      { key: "reference_no", label: "Reference" },
      { key: "subject", label: "Subject" },
      { key: "student.full_name", label: "Student" },
      { key: "priority", label: "Priority", format: "badge" },
      { key: "status", label: "Status", format: "badge" },
      { key: "created_at", label: "Created", format: "date" },
    ],
    fields: [
      { name: "student_id", label: "Student", type: "lookup", lookup: "students", displayKey: "student.full_name" },
      { name: "subject", label: "Subject", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "category", label: "Category", type: "text" },
      { name: "against", label: "Against", type: "text" },
      { name: "priority", label: "Priority", type: "select", options: [
        { value: "low", label: "Low" },
        { value: "medium", label: "Medium" },
        { value: "high", label: "High" },
      ] },
      { name: "assigned_to", label: "Assign to", type: "lookup", lookup: "staffUsers", displayKey: "assignee.name" },
    ],
    actions: [
      {
        label: "Assign",
        method: "POST",
        path: (item) => `/v1/student-affairs/complaints/${item.id}/assign`,
        permission: "student_affairs.edit",
        submitLabel: "Assign",
        successMessage: "Complaint assigned.",
        fields: [
          { name: "assigned_to", label: "Assign to", type: "lookup", lookup: "staffUsers", required: true, displayKey: "assignee.name" },
        ],
      },
      {
        label: "Resolve",
        method: "POST",
        path: (item) => `/v1/student-affairs/complaints/${item.id}/resolve`,
        permission: "student_affairs.edit",
        submitLabel: "Resolve",
        successMessage: "Complaint resolved.",
        fields: [{ name: "resolution", label: "Resolution", type: "textarea", required: true }],
      },
      {
        label: "Reject",
        method: "POST",
        path: (item) => `/v1/student-affairs/complaints/${item.id}/reject`,
        permission: "student_affairs.edit",
        confirm: "Reject this complaint?",
        submitLabel: "Reject",
        successMessage: "Complaint rejected.",
        fields: [{ name: "resolution", label: "Reason", type: "textarea", required: true }],
      },
    ],
  },
  {
    key: "sa-counselling",
    section: SECTIONS.operations,
    label: "Counselling",
    endpoint: "/v1/student-affairs/counselling",
    permissions: {
      view: "counselling.view",
      create: "counselling.create",
      edit: "counselling.edit",
      delete: "counselling.delete",
    },
    filters: [{ param: "status", label: "Status", options: [
      { value: "scheduled", label: "Scheduled" },
      { value: "completed", label: "Completed" },
      { value: "cancelled", label: "Cancelled" },
    ] }],
    columns: [
      { key: "student.full_name", label: "Student" },
      { key: "counsellor.name", label: "Counsellor" },
      { key: "type", label: "Type", format: "badge" },
      { key: "session_date", label: "Date", format: "date" },
      { key: "status", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "student_id", label: "Student", type: "lookup", lookup: "students", required: true, displayKey: "student.full_name" },
      { name: "counsellor_user_id", label: "Counsellor", type: "lookup", lookup: "staffUsers", displayKey: "counsellor.name" },
      { name: "type", label: "Type", type: "select", options: [
        { value: "individual", label: "Individual" },
        { value: "group", label: "Group" },
        { value: "follow_up", label: "Follow up" },
      ] },
      { name: "session_date", label: "Session date", type: "date", required: true },
      { name: "status", label: "Status", type: "select", options: [
        { value: "scheduled", label: "Scheduled" },
        { value: "completed", label: "Completed" },
        { value: "cancelled", label: "Cancelled" },
      ] },
      { name: "summary", label: "Summary", type: "textarea" },
      { name: "confidential_notes", label: "Confidential notes", type: "textarea" },
      { name: "follow_up_on", label: "Follow up on", type: "date" },
    ],
  },
  {
    key: "circulars",
    section: SECTIONS.operations,
    label: "Circulars",
    endpoint: "/v1/circulars",
    permissions: CIRCULAR,
    searchable: true,
    filters: [
      { param: "status", label: "Status", options: [
        { value: "draft", label: "Draft" },
        { value: "published", label: "Published" },
        { value: "archived", label: "Archived" },
      ] },
      { param: "audience", label: "Audience", options: [
        { value: "all", label: "All" },
        { value: "students", label: "Students" },
        { value: "parents", label: "Parents" },
        { value: "staff", label: "Staff" },
        { value: "class", label: "Class" },
      ] },
    ],
    columns: [
      { key: "title", label: "Title" },
      { key: "audience", label: "Audience", format: "badge" },
      { key: "status", label: "Status", format: "badge" },
      { key: "expires_on", label: "Expires", format: "date" },
      { key: "created_at", label: "Created", format: "date" },
    ],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "body", label: "Body", type: "textarea", required: true },
      { name: "audience", label: "Audience", type: "select", options: [
        { value: "all", label: "All" },
        { value: "students", label: "Students" },
        { value: "parents", label: "Parents" },
        { value: "staff", label: "Staff" },
        { value: "class", label: "Class" },
      ] },
      { name: "class_room_id", label: "Class", type: "lookup", lookup: "classRooms", displayKey: "class_room.name" },
      { name: "section_id", label: "Section", type: "number" },
      { name: "expires_on", label: "Expires on", type: "date" },
      { name: "attachment_path", label: "Attachment path", type: "text" },
    ],
    actions: [
      {
        label: "Publish",
        method: "POST",
        path: (item) => `/v1/circulars/${item.id}/publish`,
        permission: "circular.approve",
        confirm: "Publish this circular?",
        submitLabel: "Publish",
        successMessage: "Circular published.",
      },
      {
        label: "Archive",
        method: "POST",
        path: (item) => `/v1/circulars/${item.id}/archive`,
        permission: "circular.edit",
        confirm: "Archive this circular?",
        submitLabel: "Archive",
        successMessage: "Circular archived.",
      },
    ],
  },
];
