import type { ModuleConfig, SelectOption } from "./types";
import { enrollmentSection, guardianSection } from "./relations";
import { documentsSection } from "./documents";
import {
  feePlanInstallmentsSection,
  feePlanItemsSection,
  voucherLinesSection,
  voucherPaymentsSection,
} from "./feeSections";
import {
  budgetLinesSection,
  expenseLinesSection,
  journalLinesSection,
} from "./accountingSections";
import {
  payrollPayslipsSection,
  staffSalaryItemsSection,
} from "./peopleSections";

import { SECTIONS } from "./sections";
import { OPERATIONS_MODULES } from "./operations";
import { ADMINISTRATION_MODULES } from "./administration";
import { ACADEMICS_MODULES } from "./academics";

export { SECTIONS };

const YEAR_STATUS: SelectOption[] = [
  { value: "draft", label: "Draft" },
  { value: "active", label: "Active" },
  { value: "closed", label: "Closed" },
];

const BOOL_STATUS: SelectOption[] = [
  { value: "1", label: "Active" },
  { value: "0", label: "Inactive" },
];

const SUBJECT_TYPE: SelectOption[] = [
  { value: "core", label: "Core" },
  { value: "elective", label: "Elective" },
  { value: "optional", label: "Optional" },
];

const ROOM_TYPE: SelectOption[] = [
  { value: "classroom", label: "Classroom" },
  { value: "lab", label: "Lab" },
  { value: "library", label: "Library" },
  { value: "hall", label: "Hall" },
  { value: "other", label: "Other" },
];

const GENDER: SelectOption[] = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
  { value: "other", label: "Other" },
];

const GUARDIAN_RELATION: SelectOption[] = [
  { value: "father", label: "Father" },
  { value: "mother", label: "Mother" },
  { value: "guardian", label: "Guardian" },
  { value: "other", label: "Other" },
];

const STUDENT_STATUS: SelectOption[] = [
  { value: "active", label: "Active" },
  { value: "inactive", label: "Inactive" },
  { value: "withdrawn", label: "Withdrawn" },
  { value: "transferred", label: "Transferred" },
  { value: "graduated", label: "Graduated" },
];

const ENROLLMENT_STATUS: SelectOption[] = [
  { value: "active", label: "Active" },
  { value: "promoted", label: "Promoted" },
  { value: "repeated", label: "Repeated" },
  { value: "withdrawn", label: "Withdrawn" },
  { value: "transferred", label: "Transferred" },
];

const ADMISSION_STATUS: SelectOption[] = [
  { value: "enquiry", label: "Enquiry" },
  { value: "applied", label: "Applied" },
  { value: "under_review", label: "Under review" },
  { value: "approved", label: "Approved" },
  { value: "rejected", label: "Rejected" },
  { value: "enrolled", label: "Enrolled" },
];

const SCHOLARSHIP_TYPE: SelectOption[] = [
  { value: "merit", label: "Merit" },
  { value: "need_based", label: "Need based" },
  { value: "sports", label: "Sports" },
  { value: "sibling", label: "Sibling" },
  { value: "staff_ward", label: "Staff ward" },
  { value: "other", label: "Other" },
];

const DISCOUNT_TYPE: SelectOption[] = [
  { value: "percentage", label: "Percentage" },
  { value: "fixed", label: "Fixed amount" },
];

const AWARD_STATUS: SelectOption[] = [
  { value: "active", label: "Active" },
  { value: "revoked", label: "Revoked" },
];

const LATE_FEE_TYPE: SelectOption[] = [
  { value: "none", label: "None" },
  { value: "flat", label: "Flat amount" },
  { value: "percent", label: "Percentage" },
];

const VOUCHER_STATUS: SelectOption[] = [
  { value: "unpaid", label: "Unpaid" },
  { value: "partial", label: "Partial" },
  { value: "paid", label: "Paid" },
  { value: "void", label: "Void" },
];

const PAYMENT_METHOD: SelectOption[] = [
  { value: "cash", label: "Cash" },
  { value: "bank_transfer", label: "Bank transfer" },
  { value: "cheque", label: "Cheque" },
  { value: "online", label: "Online" },
  { value: "card", label: "Card" },
  { value: "other", label: "Other" },
];

const PAYMENT_STATUS: SelectOption[] = [
  { value: "draft", label: "Draft" },
  { value: "posted", label: "Posted" },
  { value: "void", label: "Void" },
];

const REFUND_STATUS: SelectOption[] = [
  { value: "pending", label: "Pending" },
  { value: "approved", label: "Approved" },
  { value: "rejected", label: "Rejected" },
  { value: "revoked", label: "Revoked" },
];

const FINE_CATEGORY: SelectOption[] = [
  { value: "library", label: "Library" },
  { value: "lab", label: "Lab" },
  { value: "discipline", label: "Discipline" },
  { value: "late_payment", label: "Late payment" },
  { value: "other", label: "Other" },
];

const FINE_STATUS: SelectOption[] = [
  { value: "pending", label: "Pending" },
  { value: "applied", label: "Applied" },
  { value: "waived", label: "Waived" },
  { value: "revoked", label: "Revoked" },
];

const REMINDER_CHANNEL: SelectOption[] = [
  { value: "email", label: "Email" },
  { value: "sms", label: "SMS" },
  { value: "in_app", label: "In-app" },
];

const REMINDER_STATUS: SelectOption[] = [
  { value: "pending", label: "Pending" },
  { value: "sent", label: "Sent" },
  { value: "failed", label: "Failed" },
  { value: "cancelled", label: "Cancelled" },
];

const CONCESSION_TYPE: SelectOption[] = [
  { value: "sibling", label: "Sibling" },
  { value: "staff_ward", label: "Staff ward" },
  { value: "need_based", label: "Need based" },
  { value: "category", label: "Category" },
  { value: "other", label: "Other" },
];

const CONCESSION_STATUS: SelectOption[] = [
  { value: "pending", label: "Pending" },
  { value: "approved", label: "Approved" },
  { value: "rejected", label: "Rejected" },
  { value: "revoked", label: "Revoked" },
];

const ACCOUNT_TYPE: SelectOption[] = [
  { value: "asset", label: "Asset" },
  { value: "liability", label: "Liability" },
  { value: "equity", label: "Equity" },
  { value: "income", label: "Income" },
  { value: "expense", label: "Expense" },
];

const NORMAL_BALANCE: SelectOption[] = [
  { value: "debit", label: "Debit" },
  { value: "credit", label: "Credit" },
];

const JOURNAL_STATUS: SelectOption[] = [
  { value: "draft", label: "Draft" },
  { value: "posted", label: "Posted" },
  { value: "reversed", label: "Reversed" },
];

const BUDGET_STATUS: SelectOption[] = [
  { value: "draft", label: "Draft" },
  { value: "approved", label: "Approved" },
  { value: "closed", label: "Closed" },
];

const BUDGET_PERIOD_TYPE: SelectOption[] = [
  { value: "annual", label: "Annual" },
  { value: "semi_annual", label: "Semi-annual" },
  { value: "quarterly", label: "Quarterly" },
  { value: "monthly", label: "Monthly" },
];

const EXPENSE_STATUS: SelectOption[] = [
  { value: "draft", label: "Draft" },
  { value: "approved", label: "Approved" },
  { value: "partial", label: "Partial" },
  { value: "paid", label: "Paid" },
  { value: "void", label: "Void" },
];

const EMPLOYMENT_TYPE: SelectOption[] = [
  { value: "permanent", label: "Permanent" },
  { value: "contract", label: "Contract" },
  { value: "part_time", label: "Part time" },
  { value: "visiting", label: "Visiting" },
  { value: "intern", label: "Intern" },
];

const STAFF_STATUS: SelectOption[] = [
  { value: "active", label: "Active" },
  { value: "probation", label: "Probation" },
  { value: "on_leave", label: "On leave" },
  { value: "resigned", label: "Resigned" },
  { value: "terminated", label: "Terminated" },
  { value: "retired", label: "Retired" },
];

const SALARY_COMPONENT_TYPE: SelectOption[] = [
  { value: "earning", label: "Earning" },
  { value: "deduction", label: "Deduction" },
];

const SALARY_CALCULATION: SelectOption[] = [
  { value: "fixed", label: "Fixed" },
  { value: "percentage_of_basic", label: "Percentage of basic" },
];

const PAYROLL_ADJUSTMENT_TYPE: SelectOption[] = [
  { value: "incentive", label: "Incentive" },
  { value: "reward", label: "Reward" },
  { value: "bonus", label: "Bonus" },
  { value: "overtime", label: "Overtime" },
  { value: "deduction", label: "Deduction" },
];

const PAYROLL_RUN_STATUS: SelectOption[] = [
  { value: "draft", label: "Draft" },
  { value: "approved", label: "Approved" },
  { value: "paid", label: "Paid" },
  { value: "cancelled", label: "Cancelled" },
];

const LEAVE_TYPE: SelectOption[] = [
  { value: "sick", label: "Sick" },
  { value: "casual", label: "Casual" },
  { value: "annual", label: "Annual" },
  { value: "maternity", label: "Maternity" },
  { value: "unpaid", label: "Unpaid" },
  { value: "other", label: "Other" },
];

const LEAVE_STATUS: SelectOption[] = [
  { value: "pending", label: "Pending" },
  { value: "approved", label: "Approved" },
  { value: "rejected", label: "Rejected" },
  { value: "cancelled", label: "Cancelled" },
];

const ADMISSION = {
  view: "admission.view",
  create: "admission.create",
  edit: "admission.edit",
  delete: "admission.delete",
  approve: "admission.approve",
};

const STUDENT = {
  view: "student.view",
  create: "student.create",
  edit: "student.edit",
  delete: "student.delete",
  approve: "student.approve",
  photo: "student.photo",
};

const SCHOLARSHIP = {
  view: "scholarship.view",
  create: "scholarship.create",
  edit: "scholarship.edit",
  delete: "scholarship.delete",
  approve: "scholarship.approve",
};

const FEE = {
  view: "fee.view",
  create: "fee.create",
  edit: "fee.edit",
  delete: "fee.delete",
  approve: "fee.approve",
};

const FINE = {
  view: "fine.view",
  create: "fine.create",
  edit: "fine.edit",
  delete: "fine.delete",
  approve: "fine.approve",
};

const REMINDER = {
  view: "reminder.view",
  create: "reminder.create",
  send: "reminder.send",
  delete: "reminder.delete",
};

const CONCESSION = {
  view: "concession.view",
  create: "concession.create",
  edit: "concession.edit",
  delete: "concession.delete",
  approve: "concession.approve",
};

const FINANCE = {
  view: "finance.view",
  create: "finance.create",
  edit: "finance.edit",
  delete: "finance.delete",
  approve: "finance.approve",
};

const HR = {
  view: "hr.view",
  create: "hr.create",
  edit: "hr.edit",
  delete: "hr.delete",
  approve: "hr.approve",
};

const PAYROLL = {
  view: "payroll.view",
  create: "payroll.create",
  edit: "payroll.edit",
  delete: "payroll.delete",
  approve: "payroll.approve",
};

const ATTENDANCE = {
  view: "attendance.view",
  create: "attendance.create",
  edit: "attendance.edit",
  approve: "attendance.approve",
};

const ACADEMIC = {
  view: "academic.view",
  create: "academic.create",
  edit: "academic.edit",
  delete: "academic.delete",
};

const CURRICULUM = {
  view: "curriculum.view",
  create: "curriculum.create",
  edit: "curriculum.edit",
  delete: "curriculum.delete",
};

export const MODULES: ModuleConfig[] = [
  {
    key: "academic-years",
    section: SECTIONS.academics,
    label: "Academic years",
    endpoint: "/v1/academic-years",
    permissions: ACADEMIC,
    searchable: true,
    filters: [
      { param: "status", label: "Status", options: YEAR_STATUS },
      {
        param: "is_current",
        label: "Current",
        options: [
          { value: "1", label: "Current" },
          { value: "0", label: "Past" },
        ],
      },
    ],
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "starts_on", label: "Starts", format: "date" },
      { key: "ends_on", label: "Ends", format: "date" },
      { key: "status", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text" },
      { name: "starts_on", label: "Starts on", type: "date", required: true },
      { name: "ends_on", label: "Ends on", type: "date", required: true },
      { name: "status", label: "Status", type: "select", options: YEAR_STATUS },
      { name: "is_current", label: "Current year", type: "checkbox" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "terms",
    section: SECTIONS.academics,
    label: "Terms",
    endpoint: "/v1/terms",
    permissions: ACADEMIC,
    columns: [
      { key: "name", label: "Name" },
      { key: "academic_year.name", label: "Academic year" },
      { key: "starts_on", label: "Starts", format: "date" },
      { key: "ends_on", label: "Ends", format: "date" },
      { key: "is_current", label: "Current", format: "badge" },
    ],
    fields: [
      {
        name: "academic_year_id",
        label: "Academic year",
        type: "lookup",
        lookup: "academicYears",
        required: true,
        displayKey: "academic_year.name",
      },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "sequence", label: "Sequence", type: "number", min: 1 },
      { name: "starts_on", label: "Starts on", type: "date", required: true },
      { name: "ends_on", label: "Ends on", type: "date", required: true },
      { name: "is_current", label: "Current term", type: "checkbox" },
    ],
  },
  {
    key: "stages",
    section: SECTIONS.academics,
    label: "Stages",
    endpoint: "/v1/stages",
    permissions: ACADEMIC,
    searchable: true,
    filters: [{ param: "is_active", label: "Status", options: BOOL_STATUS }],
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "sequence", label: "Sequence" },
      { key: "is_active", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text" },
      { name: "sequence", label: "Sequence", type: "number", min: 1 },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "classes",
    section: SECTIONS.academics,
    label: "Classes",
    endpoint: "/v1/classes",
    permissions: ACADEMIC,
    searchable: true,
    filters: [{ param: "is_active", label: "Status", options: BOOL_STATUS }],
    columns: [
      { key: "name", label: "Name" },
      { key: "stage.name", label: "Stage" },
      { key: "capacity", label: "Capacity", align: "right" },
      { key: "is_active", label: "Status", format: "badge" },
    ],
    fields: [
      {
        name: "stage_id",
        label: "Stage",
        type: "lookup",
        lookup: "stages",
        required: true,
        displayKey: "stage.name",
      },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text" },
      { name: "sequence", label: "Sequence", type: "number", min: 1 },
      { name: "capacity", label: "Capacity", type: "number", min: 0 },
      { name: "room", label: "Room", type: "text" },
      {
        name: "in_charge_user_id",
        label: "In charge",
        type: "lookup",
        lookup: "staffUsers",
        displayKey: "in_charge.name",
      },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "sections",
    section: SECTIONS.academics,
    label: "Sections",
    endpoint: "/v1/sections",
    permissions: ACADEMIC,
    filters: [{ param: "is_active", label: "Status", options: BOOL_STATUS }],
    columns: [
      { key: "name", label: "Name" },
      { key: "class_room.name", label: "Class" },
      { key: "capacity", label: "Capacity", align: "right" },
      { key: "is_active", label: "Status", format: "badge" },
    ],
    fields: [
      {
        name: "class_room_id",
        label: "Class",
        type: "lookup",
        lookup: "classRooms",
        required: true,
        displayKey: "class_room.name",
      },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "capacity", label: "Capacity", type: "number", min: 0 },
      {
        name: "in_charge_user_id",
        label: "In charge",
        type: "lookup",
        lookup: "staffUsers",
        displayKey: "in_charge.name",
      },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "subjects",
    section: SECTIONS.academics,
    label: "Subjects",
    endpoint: "/v1/subjects",
    permissions: ACADEMIC,
    searchable: true,
    filters: [
      { param: "type", label: "Type", options: SUBJECT_TYPE },
      { param: "is_active", label: "Status", options: BOOL_STATUS },
    ],
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "type", label: "Type", format: "badge" },
      { key: "credit_hours", label: "Credits", align: "right" },
      { key: "is_active", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text" },
      { name: "type", label: "Type", type: "select", options: SUBJECT_TYPE },
      { name: "credit_hours", label: "Credit hours", type: "number", min: 0, step: 0.5 },
      { name: "weekly_periods", label: "Weekly periods", type: "number", min: 0 },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "periods",
    section: SECTIONS.academics,
    label: "Periods",
    endpoint: "/v1/periods",
    permissions: ACADEMIC,
    filters: [{ param: "is_active", label: "Status", options: BOOL_STATUS }],
    columns: [
      { key: "name", label: "Name" },
      { key: "sequence", label: "Sequence" },
      { key: "starts_at", label: "Starts" },
      { key: "ends_at", label: "Ends" },
      { key: "is_break", label: "Break", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "sequence", label: "Sequence", type: "number", min: 1, required: true },
      { name: "starts_at", label: "Starts at", type: "time", required: true },
      { name: "ends_at", label: "Ends at", type: "time", required: true },
      { name: "is_break", label: "Break period", type: "checkbox" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "rooms",
    section: SECTIONS.academics,
    label: "Rooms",
    endpoint: "/v1/rooms",
    permissions: ACADEMIC,
    searchable: true,
    filters: [
      { param: "type", label: "Type", options: ROOM_TYPE },
      { param: "is_active", label: "Status", options: BOOL_STATUS },
    ],
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "block", label: "Block" },
      { key: "type", label: "Type", format: "badge" },
      { key: "capacity", label: "Capacity", align: "right" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text" },
      { name: "block", label: "Block", type: "text" },
      { name: "floor", label: "Floor", type: "text" },
      { name: "type", label: "Type", type: "select", options: ROOM_TYPE },
      { name: "capacity", label: "Capacity", type: "number", min: 0 },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "class-subjects",
    section: SECTIONS.academics,
    label: "Class subjects",
    endpoint: "/v1/class-subjects",
    permissions: ACADEMIC,
    columns: [
      { key: "class_room.name", label: "Class" },
      { key: "subject.name", label: "Subject" },
      { key: "academic_year_id", label: "Academic year" },
      { key: "is_elective", label: "Elective", format: "badge" },
    ],
    fields: [
      {
        name: "academic_year_id",
        label: "Academic year",
        type: "lookup",
        lookup: "academicYears",
        required: true,
        displayKey: "academic_year.name",
      },
      {
        name: "class_room_id",
        label: "Class",
        type: "lookup",
        lookup: "classRooms",
        required: true,
        displayKey: "class_room.name",
      },
      {
        name: "subject_id",
        label: "Subject",
        type: "lookup",
        lookup: "subjects",
        required: true,
        displayKey: "subject.name",
      },
      { name: "weekly_periods", label: "Weekly periods", type: "number", min: 0 },
      { name: "is_elective", label: "Elective", type: "checkbox" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "teaching-assignments",
    section: SECTIONS.academics,
    label: "Teaching assignments",
    endpoint: "/v1/teaching-assignments",
    permissions: ACADEMIC,
    columns: [
      { key: "teacher.name", label: "Teacher" },
      { key: "subject.name", label: "Subject" },
      { key: "class_room.name", label: "Class" },
      { key: "section.name", label: "Section" },
    ],
    fields: [
      {
        name: "academic_year_id",
        label: "Academic year",
        type: "lookup",
        lookup: "academicYears",
        required: true,
        displayKey: "academic_year.name",
      },
      {
        name: "teacher_user_id",
        label: "Teacher",
        type: "lookup",
        lookup: "staffUsers",
        required: true,
        displayKey: "teacher.name",
      },
      {
        name: "subject_id",
        label: "Subject",
        type: "lookup",
        lookup: "subjects",
        required: true,
        displayKey: "subject.name",
      },
      {
        name: "class_room_id",
        label: "Class",
        type: "lookup",
        lookup: "classRooms",
        required: true,
        displayKey: "class_room.name",
      },
      {
        name: "section_id",
        label: "Section",
        type: "lookup",
        lookup: "sections",
        dependsOn: "class_room_id",
        displayKey: "section.name",
      },
      { name: "weekly_periods", label: "Weekly periods", type: "number", min: 0 },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "syllabus-units",
    section: SECTIONS.academics,
    label: "Syllabus units",
    endpoint: "/v1/syllabus-units",
    permissions: CURRICULUM,
    columns: [
      { key: "title", label: "Title" },
      { key: "subject.name", label: "Subject" },
      { key: "class_room.name", label: "Class" },
      { key: "sequence", label: "Sequence" },
    ],
    fields: [
      {
        name: "academic_year_id",
        label: "Academic year",
        type: "lookup",
        lookup: "academicYears",
        required: true,
        displayKey: "academic_year.name",
      },
      {
        name: "class_room_id",
        label: "Class",
        type: "lookup",
        lookup: "classRooms",
        required: true,
        displayKey: "class_room.name",
      },
      {
        name: "subject_id",
        label: "Subject",
        type: "lookup",
        lookup: "subjects",
        required: true,
        displayKey: "subject.name",
      },
      {
        name: "term_id",
        label: "Term",
        type: "lookup",
        lookup: "terms",
        displayKey: "term.name",
      },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "sequence", label: "Sequence", type: "number", min: 1 },
      { name: "estimated_periods", label: "Estimated periods", type: "number", min: 0 },
    ],
  },
  {
    key: "class-books",
    section: SECTIONS.academics,
    label: "Class books",
    endpoint: "/v1/class-books",
    permissions: CURRICULUM,
    columns: [
      { key: "title", label: "Title" },
      { key: "author", label: "Author" },
      { key: "class_room.name", label: "Class" },
      { key: "price", label: "Price", format: "money", align: "right" },
      { key: "is_required", label: "Required", format: "badge" },
    ],
    fields: [
      {
        name: "academic_year_id",
        label: "Academic year",
        type: "lookup",
        lookup: "academicYears",
        required: true,
        displayKey: "academic_year.name",
      },
      {
        name: "class_room_id",
        label: "Class",
        type: "lookup",
        lookup: "classRooms",
        required: true,
        displayKey: "class_room.name",
      },
      {
        name: "subject_id",
        label: "Subject",
        type: "lookup",
        lookup: "subjects",
        displayKey: "subject.name",
      },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "author", label: "Author", type: "text" },
      { name: "publisher", label: "Publisher", type: "text" },
      { name: "isbn", label: "ISBN", type: "text" },
      { name: "edition", label: "Edition", type: "text" },
      { name: "price", label: "Price", type: "number", min: 0, step: 0.01 },
      { name: "is_required", label: "Required", type: "checkbox" },
    ],
  },
  {
    key: "admissions",
    section: SECTIONS.admissionsStudents,
    label: "Admissions",
    endpoint: "/v1/admissions",
    permissions: ADMISSION,
    searchable: true,
    filters: [{ param: "status", label: "Status", options: ADMISSION_STATUS }],
    columns: [
      { key: "application_no", label: "Application" },
      { key: "full_name", label: "Applicant" },
      { key: "class_room", label: "Class" },
      { key: "guardian_phone", label: "Guardian phone" },
      { key: "applied_on", label: "Applied", format: "date" },
      { key: "status", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "first_name", label: "First name", type: "text", required: true },
      { name: "last_name", label: "Last name", type: "text", required: true },
      { name: "gender", label: "Gender", type: "select", options: GENDER },
      { name: "date_of_birth", label: "Date of birth", type: "date" },
      {
        name: "class_room_id",
        label: "Requested class",
        type: "lookup",
        lookup: "classRooms",
        displayKey: "class_room",
      },
      {
        name: "academic_year_id",
        label: "Academic year",
        type: "lookup",
        lookup: "academicYears",
        displayKey: "academic_year",
      },
      { name: "guardian_name", label: "Guardian name", type: "text" },
      { name: "guardian_phone", label: "Guardian phone", type: "text" },
      { name: "guardian_email", label: "Guardian email", type: "email" },
      {
        name: "guardian_relation",
        label: "Guardian relation",
        type: "select",
        options: GUARDIAN_RELATION,
      },
      { name: "previous_school", label: "Previous school", type: "text" },
      { name: "address", label: "Address", type: "textarea" },
      { name: "city", label: "City", type: "text" },
      { name: "applied_on", label: "Applied on", type: "date" },
      { name: "notes", label: "Notes", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ADMISSION_STATUS,
      },
    ],
    detailSections: [
      documentsSection({
        title: "Documents",
        path: (item) => `/v1/admissions/${item.id}/documents`,
        uploadPermission: ADMISSION.create,
        deletePermission: ADMISSION.delete,
      }),
    ],
    deleteMessage: "Archive this admission?",
    actions: [
      {
        label: "Submit for review",
        path: (item) => `/v1/admissions/${item.id}/submit`,
        permission: ADMISSION.edit,
        confirm: "Submit this admission for review?",
        successMessage: "Admission submitted for review.",
      },
      {
        label: "Approve",
        path: (item) => `/v1/admissions/${item.id}/approve`,
        permission: ADMISSION.approve,
        confirm: "Approve this admission?",
        successMessage: "Admission approved.",
      },
      {
        label: "Reject",
        path: (item) => `/v1/admissions/${item.id}/reject`,
        permission: ADMISSION.approve,
        submitLabel: "Reject",
        successMessage: "Admission rejected.",
        fields: [
          {
            name: "rejection_reason",
            label: "Rejection reason",
            type: "textarea",
            required: true,
          },
        ],
      },
      {
        label: "Enroll",
        path: (item) => `/v1/admissions/${item.id}/enroll`,
        permission: ADMISSION.approve,
        submitLabel: "Enroll student",
        successMessage: "Admission enrolled.",
        fields: [
          {
            name: "academic_year_id",
            label: "Academic year",
            type: "lookup",
            lookup: "academicYears",
            required: true,
          },
          {
            name: "class_room_id",
            label: "Class",
            type: "lookup",
            lookup: "classRooms",
            required: true,
          },
          {
            name: "section_id",
            label: "Section",
            type: "lookup",
            lookup: "sections",
            dependsOn: "class_room_id",
          },
          { name: "roll_number", label: "Roll number", type: "text" },
          { name: "admission_no", label: "Admission no", type: "text" },
          { name: "gender", label: "Gender", type: "select", options: GENDER },
          { name: "starts_on", label: "Starts on", type: "date" },
        ],
      },
    ],
  },
  {
    key: "students",
    section: SECTIONS.admissionsStudents,
    label: "Students",
    endpoint: "/v1/students",
    permissions: STUDENT,
    searchable: true,
    filters: [
      { param: "status", label: "Status", options: STUDENT_STATUS },
      { param: "gender", label: "Gender", options: GENDER },
    ],
    columns: [
      { key: "admission_no", label: "Admission no" },
      { key: "full_name", label: "Name" },
      { key: "gender", label: "Gender" },
      { key: "date_of_birth", label: "Date of birth", format: "date" },
      { key: "status", label: "Status", format: "badge" },
    ],
    fields: [
      {
        name: "admission_no",
        label: "Admission no",
        type: "text",
        hint: "Leave blank to auto-generate.",
      },
      { name: "first_name", label: "First name", type: "text", required: true },
      { name: "last_name", label: "Last name", type: "text", required: true },
      { name: "gender", label: "Gender", type: "select", options: GENDER, required: true },
      { name: "date_of_birth", label: "Date of birth", type: "date" },
      { name: "blood_group", label: "Blood group", type: "text" },
      { name: "nationality", label: "Nationality", type: "text" },
      { name: "religion", label: "Religion", type: "text" },
      { name: "category", label: "Category", type: "text" },
      { name: "national_id", label: "National ID", type: "text" },
      { name: "email", label: "Email", type: "email" },
      { name: "phone", label: "Phone", type: "text" },
      { name: "city", label: "City", type: "text" },
      { name: "previous_school", label: "Previous school", type: "text" },
      { name: "admission_date", label: "Admission date", type: "date" },
      { name: "status", label: "Status", type: "select", options: STUDENT_STATUS },
      { name: "address", label: "Address", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
      {
        name: "photo_path",
        label: "Photo",
        type: "photo",
        path: "/v1/students/{id}/photo",
      },
      {
        name: "guardians",
        label: "Guardians",
        type: "repeater",
        addLabel: "Add guardian",
        hint: "Link an existing guardian or add a new one by name and phone.",
        identityKey: "guardian_id",
        titleKey: "name",
        emptyItem: () => ({
          guardian_id: "",
          name: "",
          phone: "",
          relationship: "",
          is_primary: false,
          is_emergency_contact: false,
        }),
        itemFields: [
          { name: "guardian_id", label: "Existing guardian", type: "lookup", lookup: "guardians" },
          { name: "name", label: "New guardian name", type: "text", required: true },
          { name: "phone", label: "New guardian phone", type: "text", required: true },
          {
            name: "relationship",
            label: "Relationship",
            type: "select",
            options: GUARDIAN_RELATION,
            required: true,
          },
          { name: "is_primary", label: "Primary contact", type: "checkbox" },
          { name: "is_emergency_contact", label: "Emergency contact", type: "checkbox" },
        ],
        createEndpoint: "/v1/guardians",
        createBody: (row) => {
          const name = String(row.name ?? "").trim();
          const phone = String(row.phone ?? "").trim();
          if (!name || !phone || row.guardian_id) {
            return null;
          }
          return { name, phone };
        },
        mapItem: (row, createdId) => ({
          guardian_id: createdId ?? row.guardian_id,
          relationship: row.relationship || "guardian",
          is_primary: Boolean(row.is_primary),
          is_emergency_contact: Boolean(row.is_emergency_contact),
        }),
        rowFromItem: (item) => ({
          guardian_id: item.id,
          name: item.name ?? "",
          phone: item.phone ?? "",
          relationship: item.relationship ?? "guardian",
          is_primary: Boolean(item.is_primary),
          is_emergency_contact: Boolean(item.is_emergency_contact),
        }),
      },
      {
        name: "enrollment",
        label: "Enrollment",
        type: "group",
        toggleLabel: "Enroll now",
        hint: "Optionally enroll this student immediately.",
        wrapKey: "enrollment",
        createOnly: true,
        fields: [
          {
            name: "academic_year_id",
            label: "Academic year",
            type: "lookup",
            lookup: "academicYears",
            required: true,
          },
          {
            name: "class_room_id",
            label: "Class",
            type: "lookup",
            lookup: "classRooms",
            required: true,
          },
          {
            name: "section_id",
            label: "Section",
            type: "lookup",
            lookup: "sections",
            dependsOn: "class_room_id",
          },
          { name: "roll_number", label: "Roll number", type: "text" },
        ],
      },
    ],
    detailSections: [
      guardianSection(),
      enrollmentSection(),
      documentsSection({
        title: "Documents",
        path: (item) => `/v1/students/${item.id}/documents`,
        uploadPermission: STUDENT.create,
        deletePermission: STUDENT.delete,
        verifyPermission: STUDENT.approve,
        withValidity: true,
      }),
    ],
    deleteMessage: "Archive this student?",
    actions: [
      {
        label: "Withdraw",
        path: (item) => `/v1/students/${item.id}/withdraw`,
        permission: STUDENT.approve,
        submitLabel: "Confirm withdrawal",
        successMessage: "Student withdrawn.",
        fields: [
          {
            name: "status",
            label: "Outcome",
            type: "select",
            options: [
              { value: "withdrawn", label: "Withdrawn" },
              { value: "transferred", label: "Transferred" },
            ],
          },
          { name: "date", label: "Effective date", type: "date" },
          { name: "notes", label: "Notes", type: "textarea" },
        ],
      },
    ],
  },
  {
    key: "guardians",
    section: SECTIONS.admissionsStudents,
    label: "Guardians",
    endpoint: "/v1/guardians",
    permissions: STUDENT,
    searchable: true,
    columns: [
      { key: "name", label: "Name" },
      { key: "phone", label: "Phone" },
      { key: "email", label: "Email" },
      { key: "occupation", label: "Occupation" },
      { key: "national_id", label: "National ID" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "national_id", label: "National ID", type: "text" },
      { name: "occupation", label: "Occupation", type: "text" },
      { name: "email", label: "Email", type: "email" },
      { name: "phone", label: "Phone", type: "text", required: true },
      { name: "alternate_phone", label: "Alternate phone", type: "text" },
      { name: "address", label: "Address", type: "textarea" },
    ],
    deleteMessage: "Archive this guardian?",
  },
  {
    key: "student-enrollments",
    section: SECTIONS.admissionsStudents,
    label: "Enrollments",
    endpoint: "/v1/student-enrollments",
    permissions: STUDENT,
    filters: [{ param: "status", label: "Status", options: ENROLLMENT_STATUS }],
    columns: [
      { key: "student.full_name", label: "Student" },
      { key: "academic_year.name", label: "Academic year" },
      { key: "class_room.name", label: "Class" },
      { key: "section.name", label: "Section" },
      { key: "roll_number", label: "Roll no" },
      { key: "status", label: "Status", format: "badge" },
    ],
    fields: [
      {
        name: "student_id",
        label: "Student",
        type: "lookup",
        lookup: "students",
        required: true,
        displayKey: "student.full_name",
      },
      {
        name: "academic_year_id",
        label: "Academic year",
        type: "lookup",
        lookup: "academicYears",
        required: true,
        displayKey: "academic_year.name",
      },
      {
        name: "class_room_id",
        label: "Class",
        type: "lookup",
        lookup: "classRooms",
        required: true,
        displayKey: "class_room.name",
      },
      {
        name: "section_id",
        label: "Section",
        type: "lookup",
        lookup: "sections",
        dependsOn: "class_room_id",
        displayKey: "section.name",
      },
      { name: "roll_number", label: "Roll number", type: "text" },
      { name: "status", label: "Status", type: "select", options: ENROLLMENT_STATUS },
      { name: "starts_on", label: "Starts on", type: "date" },
      { name: "ends_on", label: "Ends on", type: "date" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    deleteMessage: "Remove this enrollment?",
  },
  {
    key: "scholarships",
    section: SECTIONS.admissionsStudents,
    label: "Scholarships",
    endpoint: "/v1/scholarships",
    permissions: SCHOLARSHIP,
    searchable: true,
    filters: [
      { param: "type", label: "Type", options: SCHOLARSHIP_TYPE },
      { param: "is_active", label: "Status", options: BOOL_STATUS },
    ],
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "type_label", label: "Type" },
      {
        label: "Discount",
        align: "right",
        render: (item) => {
          const type = String(item.discount_type ?? "");
          const value = item.value ?? "";
          return `${type === "percentage" ? `${value}%` : String(value)}`;
        },
      },
      { key: "sponsor", label: "Sponsor" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text", required: true },
      {
        name: "type",
        label: "Type",
        type: "select",
        options: SCHOLARSHIP_TYPE,
        required: true,
      },
      {
        name: "discount_type",
        label: "Discount type",
        type: "select",
        options: DISCOUNT_TYPE,
        required: true,
      },
      { name: "value", label: "Value", type: "number", required: true, min: 0, step: 0.01 },
      {
        name: "academic_year_id",
        label: "Academic year",
        type: "lookup",
        lookup: "academicYears",
        displayKey: "academic_year",
      },
      { name: "sponsor", label: "Sponsor", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
    deleteMessage: "Archive this scholarship?",
  },
  {
    key: "scholarship-awards",
    section: SECTIONS.admissionsStudents,
    label: "Scholarship awards",
    endpoint: "/v1/scholarship-awards",
    permissions: SCHOLARSHIP,
    filters: [{ param: "status", label: "Status", options: AWARD_STATUS }],
    columns: [
      { key: "student.name", label: "Student" },
      { key: "scholarship.name", label: "Scholarship" },
      { key: "awarded_on", label: "Awarded", format: "date" },
      { key: "effective_value", label: "Value", align: "right" },
      { key: "status", label: "Status", format: "badge" },
    ],
    fields: [
      {
        name: "scholarship_id",
        label: "Scholarship",
        type: "lookup",
        lookup: "scholarships",
        required: true,
        displayKey: "scholarship.name",
      },
      {
        name: "student_id",
        label: "Student",
        type: "lookup",
        lookup: "students",
        required: true,
        displayKey: "student.name",
      },
      {
        name: "academic_year_id",
        label: "Academic year",
        type: "lookup",
        lookup: "academicYears",
      },
      { name: "awarded_on", label: "Awarded on", type: "date" },
      { name: "value_override", label: "Value override", type: "number", min: 0, step: 0.01 },
      { name: "status", label: "Status", type: "select", options: AWARD_STATUS },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    deleteMessage: "Archive this scholarship award?",
    actions: [
      {
        label: "Revoke",
        path: (item) => `/v1/scholarship-awards/${item.id}/revoke`,
        permission: SCHOLARSHIP.approve,
        submitLabel: "Revoke award",
        successMessage: "Scholarship award revoked.",
        fields: [{ name: "notes", label: "Notes", type: "textarea" }],
      },
    ],
  },
  {
    key: "fee-heads",
    section: SECTIONS.finance,
    label: "Fee heads",
    endpoint: "/v1/fee-heads",
    permissions: FEE,
    searchable: true,
    filters: [{ param: "is_active", label: "Status", options: BOOL_STATUS }],
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "sort_order", label: "Sort", format: "number" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "code", label: "Code", type: "text", required: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "income_account_id", label: "Income account ID", type: "number", min: 0 },
      { name: "sort_order", label: "Sort order", type: "number", min: 0 },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
    deleteMessage: "Delete this fee head?",
  },
  {
    key: "fee-plans",
    section: SECTIONS.finance,
    label: "Fee plans",
    endpoint: "/v1/fee-plans",
    permissions: FEE,
    filters: [{ param: "is_active", label: "Status", options: BOOL_STATUS }],
    columns: [
      { key: "name", label: "Name" },
      { key: "academic_year.name", label: "Year" },
      { key: "class_room.name", label: "Class" },
      { key: "totals.grand", label: "Grand total", format: "money", align: "right" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      {
        name: "academic_year_id",
        label: "Academic year",
        type: "lookup",
        lookup: "academicYears",
        required: true,
        displayKey: "academic_year.name",
      },
      {
        name: "class_room_id",
        label: "Class",
        type: "lookup",
        lookup: "classRooms",
        required: true,
        displayKey: "class_room.name",
      },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "is_active", label: "Active", type: "checkbox" },
      { name: "late_fee_type", label: "Late fee type", type: "select", options: LATE_FEE_TYPE },
      { name: "late_fee_amount", label: "Late fee amount", type: "number", min: 0, step: 0.01 },
      { name: "late_fee_grace_days", label: "Grace days", type: "number", min: 0 },
      {
        name: "items",
        label: "Fee items",
        type: "repeater",
        addLabel: "Add fee item",
        emptyItem: () => ({
          fee_head_id: "",
          amount: "",
          is_optional: false,
          sort_order: "",
        }),
        itemFields: [
          { name: "fee_head_id", label: "Fee head", type: "lookup", lookup: "feeHeads", required: true },
          { name: "amount", label: "Amount", type: "number", required: true, min: 0, step: 0.01 },
          { name: "is_optional", label: "Optional", type: "checkbox" },
          { name: "sort_order", label: "Sort order", type: "number", min: 0 },
        ],
        rowFromItem: (item) => ({
          fee_head_id: item.fee_head_id,
          amount: item.amount,
          is_optional: item.is_optional,
          sort_order: item.sort_order,
        }),
        mapItem: (row) => ({
          fee_head_id: row.fee_head_id ? Number(row.fee_head_id) : null,
          amount: Number(row.amount),
          is_optional: Boolean(row.is_optional),
          sort_order: row.sort_order === "" ? undefined : Number(row.sort_order),
        }),
      },
      {
        name: "installments",
        label: "Installments",
        type: "repeater",
        addLabel: "Add installment",
        emptyItem: () => ({ label: "", due_date: "", percentage: "" }),
        itemFields: [
          { name: "label", label: "Label", type: "text", required: true },
          { name: "due_date", label: "Due date", type: "date", required: true },
          { name: "percentage", label: "Percentage", type: "number", required: true, min: 0, max: 100, step: 0.01 },
        ],
        rowFromItem: (item) => ({
          label: item.label,
          due_date: item.due_date,
          percentage: item.percentage,
        }),
        mapItem: (row) => ({
          label: row.label,
          due_date: row.due_date,
          percentage: Number(row.percentage),
        }),
      },
    ],
    detailSections: [feePlanItemsSection, feePlanInstallmentsSection],
    deleteMessage: "Delete this fee plan?",
  },
  {
    key: "fee-vouchers",
    section: SECTIONS.finance,
    label: "Fee vouchers",
    endpoint: "/v1/fee-vouchers",
    permissions: { view: "fee.view" },
    searchable: true,
    filters: [{ param: "status", label: "Status", options: VOUCHER_STATUS }],
    headerActions: [
      {
        label: "Generate",
        path: "/v1/fee-vouchers/generate",
        permission: "fee.create",
        submitLabel: "Generate",
        successMessage: "Vouchers generated.",
        fields: [
          { name: "academic_year_id", label: "Academic year", type: "lookup", lookup: "academicYears", required: true },
          { name: "class_room_id", label: "Class", type: "lookup", lookup: "classRooms", required: true },
          { name: "fee_plan_id", label: "Fee plan", type: "lookup", lookup: "feePlans", required: true },
          { name: "apply_scholarships", label: "Apply scholarships", type: "checkbox" },
          { name: "apply_concessions", label: "Apply concessions", type: "checkbox" },
        ],
      },
      {
        label: "Generate prorated",
        path: "/v1/fee-vouchers/generate-prorated",
        permission: "fee.create",
        submitLabel: "Generate",
        successMessage: "Prorated voucher generated.",
        fields: [
          { name: "academic_year_id", label: "Academic year", type: "lookup", lookup: "academicYears", required: true },
          { name: "class_room_id", label: "Class", type: "lookup", lookup: "classRooms", required: true },
          { name: "fee_plan_id", label: "Fee plan", type: "lookup", lookup: "feePlans", required: true },
          { name: "student_id", label: "Student", type: "lookup", lookup: "students", required: true },
          { name: "join_date", label: "Join date", type: "date", required: true },
          { name: "apply_scholarships", label: "Apply scholarships", type: "checkbox" },
          { name: "apply_concessions", label: "Apply concessions", type: "checkbox" },
        ],
      },
    ],
    columns: [
      { key: "voucher_no", label: "Voucher" },
      { key: "student.full_name", label: "Student" },
      { key: "due_date", label: "Due", format: "date" },
      { key: "amount", label: "Amount", format: "money", align: "right" },
      { key: "balance", label: "Balance", format: "money", align: "right" },
      { key: "status", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "voucher_no", label: "Voucher no", type: "text", readOnly: true },
      { name: "student_id", label: "Student", type: "lookup", lookup: "students", readOnly: true, displayKey: "student.full_name" },
      { name: "due_date", label: "Due date", type: "date", readOnly: true },
      { name: "amount", label: "Amount", type: "number", readOnly: true },
      { name: "paid_amount", label: "Paid", type: "number", readOnly: true },
      { name: "balance", label: "Balance", type: "number", readOnly: true },
      { name: "status", label: "Status", type: "select", options: VOUCHER_STATUS, readOnly: true },
    ],
    detailSections: [voucherLinesSection, voucherPaymentsSection],
    actions: [
      {
        label: "Void",
        path: (item) => `/v1/fee-vouchers/${item.id}/void`,
        permission: "fee.approve",
        fields: [{ name: "memo", label: "Memo", type: "textarea" }],
        submitLabel: "Void voucher",
        successMessage: "Voucher voided.",
      },
      {
        label: "Apply late fee",
        path: (item) => `/v1/fee-vouchers/${item.id}/late-fee`,
        permission: "fee.approve",
        confirm: "Apply the late fee to this voucher?",
        submitLabel: "Apply late fee",
        successMessage: "Late fee applied.",
      },
    ],
  },
  {
    key: "fee-payments",
    section: SECTIONS.finance,
    label: "Fee payments",
    endpoint: "/v1/fee-payments",
    permissions: FEE,
    searchable: true,
    filters: [
      { param: "method", label: "Method", options: PAYMENT_METHOD },
      { param: "status", label: "Status", options: PAYMENT_STATUS },
    ],
    columns: [
      { key: "receipt_no", label: "Receipt" },
      { key: "student.full_name", label: "Student" },
      { key: "payment_date", label: "Date", format: "date" },
      { key: "amount", label: "Amount", format: "money", align: "right" },
      { key: "status", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "student_id", label: "Student", type: "lookup", lookup: "students", required: true, displayKey: "student.full_name" },
      {
        name: "fee_voucher_id",
        label: "Voucher",
        type: "lookup",
        lookup: "feeVouchers",
        required: true,
        dependsOn: "student_id",
        displayKey: "voucher.voucher_no",
      },
      { name: "payment_date", label: "Payment date", type: "date", required: true },
      { name: "amount", label: "Amount", type: "number", required: true, min: 0, step: 0.01 },
      { name: "method", label: "Method", type: "select", options: PAYMENT_METHOD, required: true },
      { name: "reference", label: "Reference", type: "text" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    actions: [
      {
        label: "Void",
        path: (item) => `/v1/fee-payments/${item.id}/void`,
        permission: "fee.approve",
        fields: [{ name: "memo", label: "Memo", type: "textarea" }],
        submitLabel: "Void payment",
        successMessage: "Payment voided.",
      },
      {
        label: "Apply",
        path: (item) => `/v1/fee-payments/${item.id}/apply`,
        permission: "fee.edit",
        confirm: "Apply this payment to the voucher?",
        submitLabel: "Apply payment",
        successMessage: "Payment applied.",
      },
    ],
  },
  {
    key: "fee-refunds",
    section: SECTIONS.finance,
    label: "Fee refunds",
    endpoint: "/v1/fee-refunds",
    permissions: FEE,
    filters: [{ param: "approval_status", label: "Status", options: REFUND_STATUS }],
    columns: [
      { key: "student.name", label: "Student" },
      { key: "refund_date", label: "Date", format: "date" },
      { key: "amount", label: "Amount", format: "money", align: "right" },
      { key: "approval_status", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "student_id", label: "Student", type: "lookup", lookup: "students", required: true, displayKey: "student.name" },
      {
        name: "fee_payment_id",
        label: "Payment",
        type: "lookup",
        lookup: "feePayments",
        required: true,
        dependsOn: "student_id",
        displayKey: "payment.receipt_no",
      },
      { name: "refund_date", label: "Refund date", type: "date", required: true },
      { name: "amount", label: "Amount", type: "number", required: true, min: 0, step: 0.01 },
      { name: "method", label: "Method", type: "select", options: PAYMENT_METHOD, required: true },
      { name: "reason", label: "Reason", type: "text" },
    ],
    actions: [
      {
        label: "Approve",
        path: (item) => `/v1/fee-refunds/${item.id}/approve`,
        permission: "fee.approve",
        fields: [{ name: "decision_note", label: "Decision note", type: "textarea" }],
        submitLabel: "Approve refund",
        successMessage: "Refund approved.",
      },
      {
        label: "Reject",
        path: (item) => `/v1/fee-refunds/${item.id}/reject`,
        permission: "fee.approve",
        confirm: "Reject this refund?",
        fields: [{ name: "decision_note", label: "Decision note", type: "textarea" }],
        submitLabel: "Reject refund",
        successMessage: "Refund rejected.",
      },
      {
        label: "Revoke",
        path: (item) => `/v1/fee-refunds/${item.id}/revoke`,
        permission: "fee.approve",
        confirm: "Revoke this refund?",
        fields: [{ name: "decision_note", label: "Decision note", type: "textarea" }],
        submitLabel: "Revoke refund",
        successMessage: "Refund revoked.",
      },
    ],
  },
  {
    key: "fine-rules",
    section: SECTIONS.finance,
    label: "Fine rules",
    endpoint: "/v1/fine-rules",
    permissions: FINE,
    searchable: true,
    filters: [
      { param: "category", label: "Category", options: FINE_CATEGORY },
      { param: "is_active", label: "Status", options: BOOL_STATUS },
    ],
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "category_label", label: "Category" },
      { key: "amount", label: "Amount", format: "money", align: "right" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text", required: true },
      { name: "category", label: "Category", type: "select", options: FINE_CATEGORY, required: true },
      { name: "amount", label: "Amount", type: "number", required: true, min: 0, step: 0.01 },
      { name: "fee_head_id", label: "Fee head", type: "lookup", lookup: "feeHeads" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
    deleteMessage: "Delete this fine rule?",
  },
  {
    key: "student-fines",
    section: SECTIONS.finance,
    label: "Student fines",
    endpoint: "/v1/fines",
    permissions: { view: "fine.view", create: "fine.create" },
    filters: [{ param: "status", label: "Status", options: FINE_STATUS }],
    columns: [
      { key: "student.name", label: "Student" },
      { key: "rule.name", label: "Rule" },
      { key: "amount", label: "Amount", format: "money", align: "right" },
      { key: "issued_on", label: "Issued", format: "date" },
      { key: "status", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "student_id", label: "Student", type: "lookup", lookup: "students", required: true, displayKey: "student.name" },
      { name: "fine_rule_id", label: "Fine rule", type: "lookup", lookup: "fineRules", displayKey: "rule.name" },
      { name: "academic_year_id", label: "Academic year", type: "lookup", lookup: "academicYears" },
      {
        name: "fee_voucher_id",
        label: "Voucher",
        type: "lookup",
        lookup: "feeVouchers",
        dependsOn: "student_id",
        displayKey: "voucher_no",
      },
      { name: "amount", label: "Amount", type: "number", min: 0, step: 0.01 },
      { name: "reason", label: "Reason", type: "text" },
      { name: "issued_on", label: "Issued on", type: "date", required: true },
    ],
    actions: [
      {
        label: "Apply",
        path: (item) => `/v1/fines/${item.id}/apply`,
        permission: "fine.approve",
        confirm: "Apply this fine to the student's voucher?",
        submitLabel: "Apply fine",
        successMessage: "Fine applied.",
      },
      {
        label: "Waive",
        path: (item) => `/v1/fines/${item.id}/waive`,
        permission: "fine.approve",
        fields: [{ name: "waived_reason", label: "Waived reason", type: "textarea" }],
        submitLabel: "Waive fine",
        successMessage: "Fine waived.",
      },
      {
        label: "Revoke",
        path: (item) => `/v1/fines/${item.id}/revoke`,
        permission: "fine.approve",
        confirm: "Revoke this fine?",
        fields: [{ name: "reason", label: "Reason", type: "textarea" }],
        submitLabel: "Revoke fine",
        successMessage: "Fine revoked.",
      },
    ],
  },
  {
    key: "fee-reminders",
    section: SECTIONS.finance,
    label: "Fee reminders",
    endpoint: "/v1/fee-reminders",
    permissions: REMINDER,
    filters: [
      { param: "status", label: "Status", options: REMINDER_STATUS },
      { param: "channel", label: "Channel", options: REMINDER_CHANNEL },
    ],
    headerActions: [
      {
        label: "Run reminders",
        path: "/v1/fee-reminders",
        permission: "reminder.create",
        submitLabel: "Create reminders",
        successMessage: "Reminders generated.",
        fields: [
          { name: "academic_year_id", label: "Academic year", type: "lookup", lookup: "academicYears" },
          { name: "class_room_id", label: "Class", type: "lookup", lookup: "classRooms" },
          { name: "channel", label: "Channel", type: "select", options: REMINDER_CHANNEL },
          { name: "overdue_only", label: "Overdue only", type: "checkbox" },
          { name: "min_days_overdue", label: "Min days overdue", type: "number", min: 0 },
          { name: "min_balance", label: "Min balance", type: "number", min: 0, step: 0.01 },
          { name: "as_of", label: "As of", type: "date" },
          { name: "force", label: "Force", type: "checkbox" },
        ],
      },
      {
        label: "Send pending",
        path: "/v1/fee-reminders/send",
        permission: "reminder.send",
        submitLabel: "Send reminders",
        successMessage: "Reminders sent.",
        fields: [{ name: "academic_year_id", label: "Academic year", type: "lookup", lookup: "academicYears" }],
      },
    ],
    columns: [
      { key: "student", label: "Student" },
      { key: "guardian", label: "Guardian" },
      { key: "channel_label", label: "Channel" },
      { key: "outstanding", label: "Outstanding", format: "money", align: "right" },
      { key: "days_overdue", label: "Days", format: "number" },
      { key: "status_label", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "student_id", label: "Student", type: "lookup", lookup: "students", readOnly: true, displayKey: "student" },
      { name: "channel", label: "Channel", type: "select", options: REMINDER_CHANNEL, readOnly: true },
      { name: "outstanding", label: "Outstanding", type: "number", readOnly: true },
      { name: "days_overdue", label: "Days overdue", type: "number", readOnly: true },
      { name: "status", label: "Status", type: "select", options: REMINDER_STATUS, readOnly: true },
    ],
    actions: [
      {
        label: "Send",
        path: (item) => `/v1/fee-reminders/${item.id}/send`,
        permission: "reminder.send",
        confirm: "Send this reminder?",
        submitLabel: "Send",
        successMessage: "Reminder sent.",
      },
      {
        label: "Cancel",
        path: (item) => `/v1/fee-reminders/${item.id}/cancel`,
        permission: "reminder.send",
        confirm: "Cancel this reminder?",
        submitLabel: "Cancel reminder",
        successMessage: "Reminder cancelled.",
      },
    ],
  },
  {
    key: "concession-policies",
    section: SECTIONS.finance,
    label: "Concession policies",
    endpoint: "/v1/concession-policies",
    permissions: CONCESSION,
    searchable: true,
    filters: [
      { param: "type", label: "Type", options: CONCESSION_TYPE },
      { param: "is_active", label: "Status", options: BOOL_STATUS },
    ],
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "type_label", label: "Type" },
      {
        label: "Discount",
        align: "right",
        render: (item) =>
          `${item.discount_type === "percentage" ? `${item.value}%` : String(item.value ?? "")}`,
      },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text", required: true },
      { name: "type", label: "Type", type: "select", options: CONCESSION_TYPE, required: true },
      { name: "discount_type", label: "Discount type", type: "select", options: DISCOUNT_TYPE, required: true },
      { name: "value", label: "Value", type: "number", required: true, min: 0, step: 0.01 },
      { name: "max_amount", label: "Max amount", type: "number", min: 0, step: 0.01 },
      { name: "priority", label: "Priority", type: "number", min: 0 },
      { name: "academic_year_id", label: "Academic year", type: "lookup", lookup: "academicYears", displayKey: "academic_year" },
      { name: "class_room_id", label: "Class", type: "lookup", lookup: "classRooms", displayKey: "class_room" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "is_stackable", label: "Stackable", type: "checkbox" },
      { name: "requires_approval", label: "Requires approval", type: "checkbox" },
      { name: "is_active", label: "Active", type: "checkbox" },
      {
        name: "criteria",
        label: "Eligibility criteria",
        type: "group",
        toggleLabel: "Limit eligibility",
        wrapKey: "criteria",
        fields: [
          {
            name: "gender",
            label: "Gender",
            type: "multiselect",
            options: [
              { value: "male", label: "Male" },
              { value: "female", label: "Female" },
              { value: "other", label: "Other" },
            ],
          },
          { name: "min_siblings", label: "Min siblings", type: "number", min: 1 },
        ],
      },
    ],
    deleteMessage: "Delete this concession policy?",
  },
  {
    key: "concessions",
    section: SECTIONS.finance,
    label: "Concessions",
    endpoint: "/v1/concessions",
    permissions: CONCESSION,
    filters: [{ param: "status", label: "Status", options: CONCESSION_STATUS }],
    columns: [
      { key: "student.name", label: "Student" },
      { key: "policy.name", label: "Policy" },
      { key: "amount", label: "Amount", format: "money", align: "right" },
      { key: "status", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "student_id", label: "Student", type: "lookup", lookup: "students", required: true, displayKey: "student.name" },
      { name: "academic_year_id", label: "Academic year", type: "lookup", lookup: "academicYears", required: true, displayKey: "academic_year" },
      { name: "concession_policy_id", label: "Policy", type: "lookup", lookup: "concessionPolicies", displayKey: "policy.name" },
      { name: "discount_type", label: "Discount type", type: "select", options: DISCOUNT_TYPE },
      { name: "value", label: "Value", type: "number", min: 0, step: 0.01 },
      { name: "amount", label: "Amount", type: "number", min: 0, step: 0.01 },
      { name: "note", label: "Note", type: "textarea" },
    ],
    actions: [
      {
        label: "Approve",
        path: (item) => `/v1/concessions/${item.id}/approve`,
        permission: "concession.approve",
        confirm: "Approve this concession?",
        submitLabel: "Approve",
        successMessage: "Concession approved.",
      },
      {
        label: "Reject",
        path: (item) => `/v1/concessions/${item.id}/reject`,
        permission: "concession.approve",
        confirm: "Reject this concession?",
        submitLabel: "Reject",
        successMessage: "Concession rejected.",
      },
      {
        label: "Revoke",
        path: (item) => `/v1/concessions/${item.id}/revoke`,
        permission: "concession.approve",
        confirm: "Revoke this concession?",
        submitLabel: "Revoke",
        successMessage: "Concession revoked.",
      },
    ],
  },
  {
    key: "chart-of-accounts",
    section: SECTIONS.finance,
    label: "Chart of accounts",
    endpoint: "/v1/chart-of-accounts",
    permissions: FINANCE,
    searchable: true,
    filters: [
      { param: "account_type", label: "Type", options: ACCOUNT_TYPE },
      { param: "is_active", label: "Status", options: BOOL_STATUS },
    ],
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "account_type", label: "Type" },
      { key: "normal_balance", label: "Balance" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "code", label: "Code", type: "text", required: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "account_type", label: "Account type", type: "select", options: ACCOUNT_TYPE, required: true },
      { name: "normal_balance", label: "Normal balance", type: "select", options: NORMAL_BALANCE },
      { name: "parent_id", label: "Parent account", type: "lookup", lookup: "chartOfAccounts" },
      { name: "is_group", label: "Group account", type: "checkbox" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
      { name: "description", label: "Description", type: "textarea" },
    ],
    deleteMessage: "Delete this account?",
  },
  {
    key: "expense-categories",
    section: SECTIONS.finance,
    label: "Expense categories",
    endpoint: "/v1/expense-categories",
    permissions: FINANCE,
    searchable: true,
    filters: [{ param: "is_active", label: "Status", options: BOOL_STATUS }],
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "expense_account.name", label: "Account" },
      { key: "sort_order", label: "Sort", format: "number" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "code", label: "Code", type: "text", required: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "expense_account_id", label: "Expense account", type: "lookup", lookup: "chartOfAccounts" },
      { name: "sort_order", label: "Sort order", type: "number", min: 0 },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
    deleteMessage: "Delete this expense category?",
  },
  {
    key: "vendors",
    section: SECTIONS.finance,
    label: "Vendors",
    endpoint: "/v1/vendors",
    permissions: FINANCE,
    searchable: true,
    filters: [{ param: "is_active", label: "Status", options: BOOL_STATUS }],
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "contact_name", label: "Contact" },
      { key: "phone", label: "Phone" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "code", label: "Code", type: "text", required: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "contact_name", label: "Contact name", type: "text" },
      { name: "phone", label: "Phone", type: "text" },
      { name: "email", label: "Email", type: "email" },
      { name: "tax_number", label: "Tax number", type: "text" },
      { name: "address", label: "Address", type: "text" },
      { name: "notes", label: "Notes", type: "textarea" },
      { name: "payable_account_id", label: "Payable account", type: "lookup", lookup: "chartOfAccounts" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
    deleteMessage: "Delete this vendor?",
  },
  {
    key: "budgets",
    section: SECTIONS.finance,
    label: "Budgets",
    endpoint: "/v1/budgets",
    permissions: FINANCE,
    searchable: true,
    filters: [{ param: "status", label: "Status", options: BUDGET_STATUS }],
    columns: [
      { key: "name", label: "Name" },
      { key: "fiscal_year.name", label: "Fiscal year" },
      { key: "period_type", label: "Period" },
      { key: "starts_on", label: "Starts", format: "date" },
      { key: "ends_on", label: "Ends", format: "date" },
      { key: "total_budget", label: "Budget", format: "money", align: "right" },
      { key: "status", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "fiscal_year_id", label: "Fiscal year", type: "lookup", lookup: "fiscalYears", required: true, displayKey: "fiscal_year.name" },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "period_type", label: "Period type", type: "select", options: BUDGET_PERIOD_TYPE, required: true },
      { name: "starts_on", label: "Starts on", type: "date", required: true },
      { name: "ends_on", label: "Ends on", type: "date", required: true },
      { name: "notes", label: "Notes", type: "textarea" },
      {
        name: "lines",
        label: "Budget lines",
        type: "repeater",
        addLabel: "Add budget line",
        emptyItem: () => ({ chart_of_account_id: "", amount: "", notes: "" }),
        itemFields: [
          { name: "chart_of_account_id", label: "Account", type: "lookup", lookup: "chartOfAccounts", required: true },
          { name: "amount", label: "Amount", type: "number", required: true, min: 0, step: 0.01 },
          { name: "notes", label: "Notes", type: "text" },
        ],
        rowFromItem: (item) => ({
          chart_of_account_id: item.chart_of_account_id,
          amount: item.amount,
          notes: item.notes,
        }),
        mapItem: (row) => ({
          chart_of_account_id: row.chart_of_account_id ? Number(row.chart_of_account_id) : null,
          amount: Number(row.amount),
          notes: row.notes,
        }),
      },
    ],
    detailSections: [budgetLinesSection],
    deleteMessage: "Delete this budget?",
    actions: [
      {
        label: "Approve",
        path: (item) => `/v1/budgets/${item.id}/approve`,
        permission: "finance.approve",
        confirm: "Approve this budget?",
        submitLabel: "Approve",
        successMessage: "Budget approved.",
      },
    ],
  },
  {
    key: "journal-entries",
    section: SECTIONS.finance,
    label: "Journal",
    endpoint: "/v1/journal-entries",
    permissions: FINANCE,
    searchable: true,
    filters: [{ param: "status", label: "Status", options: JOURNAL_STATUS }],
    columns: [
      { key: "reference", label: "Reference" },
      { key: "entry_date", label: "Date", format: "date" },
      { key: "total_debit", label: "Debit", format: "money", align: "right" },
      { key: "total_credit", label: "Credit", format: "money", align: "right" },
      { key: "status", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "fiscal_year_id", label: "Fiscal year", type: "lookup", lookup: "fiscalYears", required: true, displayKey: "fiscal_year.name" },
      { name: "reference", label: "Reference", type: "text", required: true },
      { name: "entry_date", label: "Entry date", type: "date", required: true },
      { name: "memo", label: "Memo", type: "textarea" },
      {
        name: "lines",
        label: "Journal lines",
        type: "repeater",
        addLabel: "Add journal line",
        hint: "Enter at least two lines; total debits must equal total credits.",
        emptyItem: () => ({ chart_of_account_id: "", description: "", debit: "", credit: "" }),
        itemFields: [
          { name: "chart_of_account_id", label: "Account", type: "lookup", lookup: "chartOfAccounts", required: true },
          { name: "description", label: "Description", type: "text" },
          { name: "debit", label: "Debit", type: "number", min: 0, step: 0.01 },
          { name: "credit", label: "Credit", type: "number", min: 0, step: 0.01 },
        ],
        rowFromItem: (item) => ({
          chart_of_account_id: item.chart_of_account_id,
          description: item.description,
          debit: item.debit,
          credit: item.credit,
        }),
        mapItem: (row) => ({
          chart_of_account_id: row.chart_of_account_id ? Number(row.chart_of_account_id) : null,
          description: row.description,
          debit: row.debit === "" ? undefined : Number(row.debit),
          credit: row.credit === "" ? undefined : Number(row.credit),
        }),
      },
    ],
    detailSections: [journalLinesSection],
    deleteMessage: "Delete this journal entry?",
    actions: [
      {
        label: "Post",
        path: (item) => `/v1/journal-entries/${item.id}/post`,
        permission: "finance.approve",
        confirm: "Post this journal entry?",
        submitLabel: "Post entry",
        successMessage: "Journal entry posted.",
      },
      {
        label: "Reverse",
        path: (item) => `/v1/journal-entries/${item.id}/reverse`,
        permission: "finance.approve",
        fields: [{ name: "memo", label: "Memo", type: "textarea" }],
        submitLabel: "Reverse entry",
        successMessage: "Journal entry reversed.",
      },
    ],
  },
  {
    key: "expenses",
    section: SECTIONS.finance,
    label: "Expenses",
    endpoint: "/v1/expenses",
    permissions: FINANCE,
    searchable: true,
    filters: [{ param: "status", label: "Status", options: EXPENSE_STATUS }],
    columns: [
      { key: "reference", label: "Reference" },
      { key: "vendor.name", label: "Vendor" },
      { key: "expense_date", label: "Date", format: "date" },
      { key: "total", label: "Total", format: "money", align: "right" },
      { key: "paid_amount", label: "Paid", format: "money", align: "right" },
      { key: "status_label", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "vendor_id", label: "Vendor", type: "lookup", lookup: "vendors", displayKey: "vendor.name" },
      { name: "fiscal_year_id", label: "Fiscal year", type: "lookup", lookup: "fiscalYears", displayKey: "fiscal_year.name" },
      { name: "expense_date", label: "Expense date", type: "date", required: true },
      { name: "reference", label: "Reference", type: "text" },
      { name: "payee_name", label: "Payee name", type: "text" },
      { name: "bill_no", label: "Bill no", type: "text" },
      { name: "memo", label: "Memo", type: "textarea" },
      {
        name: "lines",
        label: "Expense lines",
        type: "repeater",
        addLabel: "Add expense line",
        emptyItem: () => ({ expense_category_id: "", amount: "", description: "" }),
        itemFields: [
          { name: "expense_category_id", label: "Category", type: "lookup", lookup: "expenseCategories", required: true },
          { name: "amount", label: "Amount", type: "number", required: true, min: 0, step: 0.01 },
          { name: "description", label: "Description", type: "text" },
        ],
        rowFromItem: (item) => ({
          expense_category_id: item.expense_category_id,
          amount: item.amount,
          description: item.description,
        }),
        mapItem: (row) => ({
          expense_category_id: row.expense_category_id ? Number(row.expense_category_id) : null,
          amount: Number(row.amount),
          description: row.description,
        }),
      },
    ],
    detailSections: [expenseLinesSection],
    deleteMessage: "Delete this expense?",
    actions: [
      {
        label: "Approve",
        path: (item) => `/v1/expenses/${item.id}/approve`,
        permission: "finance.approve",
        confirm: "Approve this expense?",
        submitLabel: "Approve",
        successMessage: "Expense approved.",
      },
      {
        label: "Void",
        path: (item) => `/v1/expenses/${item.id}/void`,
        permission: "finance.approve",
        fields: [{ name: "memo", label: "Memo", type: "textarea" }],
        submitLabel: "Void expense",
        successMessage: "Expense voided.",
      },
    ],
  },
  {
    key: "departments",
    section: SECTIONS.people,
    label: "Departments",
    endpoint: "/v1/departments",
    permissions: HR,
    filters: [{ param: "is_active", label: "Status", options: BOOL_STATUS }],
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "head.name", label: "Head" },
      { key: "designations_count", label: "Designations", format: "number" },
      { key: "staff_count", label: "Staff", format: "number" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text", required: true },
      { name: "head_user_id", label: "Head", type: "lookup", lookup: "staffUsers" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
    deleteMessage: "Delete this department?",
  },
  {
    key: "designations",
    section: SECTIONS.people,
    label: "Designations",
    endpoint: "/v1/designations",
    permissions: HR,
    filters: [{ param: "is_active", label: "Status", options: BOOL_STATUS }],
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "department.name", label: "Department" },
      { key: "grade", label: "Grade" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text", required: true },
      { name: "department_id", label: "Department", type: "lookup", lookup: "departments" },
      { name: "grade", label: "Grade", type: "text" },
      { name: "job_description", label: "Job description", type: "textarea" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
    deleteMessage: "Delete this designation?",
  },
  {
    key: "staff",
    section: SECTIONS.people,
    label: "Staff",
    endpoint: "/v1/staff",
    permissions: HR,
    searchable: true,
    filters: [
      { param: "status", label: "Status", options: STAFF_STATUS },
      { param: "employment_type", label: "Type", options: EMPLOYMENT_TYPE },
    ],
    columns: [
      { key: "employee_no", label: "Employee no" },
      { key: "full_name", label: "Name" },
      { key: "department.name", label: "Department" },
      { key: "designation.name", label: "Designation" },
      { key: "employment_type_label", label: "Type" },
      { key: "status_label", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "first_name", label: "First name", type: "text", required: true },
      { name: "last_name", label: "Last name", type: "text" },
      { name: "employee_no", label: "Employee no", type: "text" },
      { name: "user_id", label: "Login", type: "lookup", lookup: "staffUsers" },
      { name: "department_id", label: "Department", type: "lookup", lookup: "departments" },
      { name: "designation_id", label: "Designation", type: "lookup", lookup: "designations" },
      { name: "gender", label: "Gender", type: "select", options: GENDER },
      { name: "date_of_birth", label: "Date of birth", type: "date" },
      { name: "cnic", label: "CNIC", type: "text" },
      { name: "phone", label: "Phone", type: "text" },
      { name: "email", label: "Email", type: "email" },
      { name: "address", label: "Address", type: "text" },
      { name: "emergency_contact_name", label: "Emergency contact", type: "text" },
      { name: "emergency_contact_phone", label: "Emergency phone", type: "text" },
      { name: "employment_type", label: "Employment type", type: "select", options: EMPLOYMENT_TYPE },
      { name: "status", label: "Status", type: "select", options: STAFF_STATUS },
      { name: "joining_date", label: "Joining date", type: "date", required: true },
      { name: "leaving_date", label: "Leaving date", type: "date" },
      { name: "bank_name", label: "Bank name", type: "text" },
      { name: "bank_account_no", label: "Bank account no", type: "text" },
      { name: "tax_number", label: "Tax number", type: "text" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    detailSections: [
      documentsSection({
        title: "Documents",
        path: (item) => `/v1/staff/${item.id}/documents`,
        withValidity: true,
        uploadPermission: "hr.create",
        deletePermission: "hr.delete",
        verifyPermission: "hr.approve",
      }),
    ],
    deleteMessage: "Delete this staff member?",
    actions: [
      {
        label: "Terminate",
        path: (item) => `/v1/staff/${item.id}/terminate`,
        permission: "hr.approve",
        fields: [
          { name: "leaving_date", label: "Leaving date", type: "date", required: true },
          { name: "status", label: "Status", type: "select", options: STAFF_STATUS },
          { name: "reason", label: "Reason", type: "textarea" },
        ],
        submitLabel: "Terminate",
        successMessage: "Staff member terminated.",
      },
    ],
  },
  {
    key: "salary-components",
    section: SECTIONS.people,
    label: "Salary components",
    endpoint: "/v1/salary-components",
    permissions: PAYROLL,
    filters: [
      { param: "type", label: "Type", options: SALARY_COMPONENT_TYPE },
      { param: "is_active", label: "Status", options: BOOL_STATUS },
    ],
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "type_label", label: "Type" },
      { key: "calculation", label: "Calculation" },
      { key: "default_amount", label: "Default", format: "money", align: "right" },
      { key: "is_taxable", label: "Taxable", format: "badge" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text", required: true },
      { name: "type", label: "Type", type: "select", options: SALARY_COMPONENT_TYPE, required: true },
      { name: "calculation", label: "Calculation", type: "select", options: SALARY_CALCULATION },
      { name: "default_amount", label: "Default amount", type: "number", min: 0, step: 0.01 },
      { name: "default_percentage", label: "Default percentage", type: "number", min: 0, max: 100 },
      { name: "is_taxable", label: "Taxable", type: "checkbox" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
      { name: "sort_order", label: "Sort order", type: "number", min: 0 },
    ],
    deleteMessage: "Delete this salary component?",
  },
  {
    key: "staff-salaries",
    section: SECTIONS.people,
    label: "Staff salaries",
    endpoint: "/v1/staff-salaries",
    permissions: PAYROLL,
    filters: [{ param: "is_active", label: "Status", options: BOOL_STATUS }],
    columns: [
      { key: "staff_member.full_name", label: "Staff" },
      { key: "basic_salary", label: "Basic", format: "money", align: "right" },
      { key: "currency", label: "Currency" },
      { key: "effective_from", label: "From", format: "date" },
      { key: "effective_to", label: "To", format: "date" },
      { key: "is_active", label: "Active", format: "badge" },
    ],
    fields: [
      { name: "staff_member_id", label: "Staff", type: "lookup", lookup: "staffMembers", required: true, displayKey: "staff_member.full_name" },
      { name: "basic_salary", label: "Basic salary", type: "number", required: true, min: 0, step: 0.01 },
      { name: "currency", label: "Currency", type: "text" },
      { name: "effective_from", label: "Effective from", type: "date", required: true },
      { name: "effective_to", label: "Effective to", type: "date" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
      { name: "notes", label: "Notes", type: "textarea" },
      {
        name: "items",
        label: "Components",
        type: "repeater",
        addLabel: "Add component",
        emptyItem: () => ({ salary_component_id: "", amount: "", percentage: "" }),
        itemFields: [
          { name: "salary_component_id", label: "Component", type: "lookup", lookup: "salaryComponents", required: true },
          { name: "amount", label: "Amount", type: "number", min: 0, step: 0.01 },
          { name: "percentage", label: "Percentage", type: "number", min: 0, max: 100 },
        ],
        rowFromItem: (item) => ({
          salary_component_id: item.salary_component_id,
          amount: item.amount,
          percentage: item.percentage,
        }),
        mapItem: (row) => ({
          salary_component_id: row.salary_component_id ? Number(row.salary_component_id) : null,
          amount: row.amount === "" ? undefined : Number(row.amount),
          percentage: row.percentage === "" ? undefined : Number(row.percentage),
        }),
      },
    ],
    detailSections: [staffSalaryItemsSection],
    deleteMessage: "Delete this salary structure?",
  },
  {
    key: "payroll-adjustments",
    section: SECTIONS.people,
    label: "Payroll adjustments",
    endpoint: "/v1/payroll-adjustments",
    permissions: PAYROLL,
    filters: [
      { param: "type", label: "Type", options: PAYROLL_ADJUSTMENT_TYPE },
      { param: "is_applied", label: "Applied", options: BOOL_STATUS },
    ],
    columns: [
      { key: "staff_member.full_name", label: "Staff" },
      { key: "type_label", label: "Type" },
      { key: "amount", label: "Amount", format: "money", align: "right" },
      { key: "period", label: "Period" },
      { key: "reason", label: "Reason" },
      { key: "is_applied", label: "Applied", format: "badge" },
    ],
    fields: [
      { name: "staff_member_id", label: "Staff", type: "lookup", lookup: "staffMembers", required: true, displayKey: "staff_member.full_name" },
      { name: "type", label: "Type", type: "select", options: PAYROLL_ADJUSTMENT_TYPE, required: true },
      { name: "amount", label: "Amount", type: "number", required: true, min: 0, step: 0.01 },
      { name: "period", label: "Period", type: "text", required: true, hint: "Format YYYY-MM, e.g. 2026-01." },
      { name: "reason", label: "Reason", type: "text" },
    ],
    deleteMessage: "Delete this payroll adjustment?",
  },
  {
    key: "payroll-runs",
    section: SECTIONS.people,
    label: "Payroll runs",
    endpoint: "/v1/payroll-runs",
    permissions: PAYROLL,
    filters: [{ param: "status", label: "Status", options: PAYROLL_RUN_STATUS }],
    columns: [
      { key: "period", label: "Period" },
      { key: "status_label", label: "Status", format: "badge" },
      { key: "payslips_count", label: "Payslips", format: "number" },
      { key: "total_gross", label: "Gross", format: "money", align: "right" },
      { key: "total_deductions", label: "Deductions", format: "money", align: "right" },
      { key: "total_net", label: "Net", format: "money", align: "right" },
    ],
    fields: [
      { name: "period", label: "Period", type: "text", required: true, hint: "Format YYYY-MM, e.g. 2026-01." },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    detailSections: [payrollPayslipsSection],
    deleteMessage: "Delete this payroll run?",
    actions: [
      {
        label: "Generate",
        path: (item) => `/v1/payroll-runs/${item.id}/generate`,
        permission: "payroll.edit",
        confirm: "Generate payslips for this payroll run?",
        submitLabel: "Generate",
        successMessage: "Payroll generated.",
      },
      {
        label: "Approve",
        path: (item) => `/v1/payroll-runs/${item.id}/approve`,
        permission: "payroll.approve",
        confirm: "Approve this payroll run?",
        submitLabel: "Approve",
        successMessage: "Payroll approved.",
      },
      {
        label: "Pay",
        path: (item) => `/v1/payroll-runs/${item.id}/pay`,
        permission: "payroll.approve",
        fields: [{ name: "payment_method", label: "Payment method", type: "select", options: PAYMENT_METHOD, required: true }],
        submitLabel: "Mark paid",
        successMessage: "Payroll marked as paid.",
      },
    ],
  },
  {
    key: "leave-requests",
    section: SECTIONS.people,
    label: "Leave requests",
    endpoint: "/v1/leave-requests",
    permissions: ATTENDANCE,
    filters: [
      { param: "status", label: "Status", options: LEAVE_STATUS },
      { param: "leave_type", label: "Type", options: LEAVE_TYPE },
    ],
    columns: [
      { key: "user.name", label: "Staff" },
      { key: "leave_type_label", label: "Type" },
      { key: "from_date", label: "From", format: "date" },
      { key: "to_date", label: "To", format: "date" },
      { key: "days", label: "Days", format: "number" },
      { key: "status_label", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "user_id", label: "Staff", type: "lookup", lookup: "staffUsers" },
      { name: "leave_type", label: "Leave type", type: "select", options: LEAVE_TYPE, required: true },
      { name: "from_date", label: "From date", type: "date", required: true },
      { name: "to_date", label: "To date", type: "date", required: true },
      { name: "days", label: "Days", type: "number", min: 0.5, step: 0.5 },
      { name: "reason", label: "Reason", type: "textarea" },
    ],
    deleteMessage: "Delete this leave request?",
    actions: [
      {
        label: "Approve",
        path: (item) => `/v1/leave-requests/${item.id}/approve`,
        permission: "attendance.approve",
        fields: [{ name: "decision_note", label: "Note", type: "textarea" }],
        submitLabel: "Approve",
        successMessage: "Leave request approved.",
      },
      {
        label: "Reject",
        path: (item) => `/v1/leave-requests/${item.id}/reject`,
        permission: "attendance.approve",
        fields: [{ name: "decision_note", label: "Note", type: "textarea" }],
        submitLabel: "Reject",
        successMessage: "Leave request rejected.",
      },
      {
        label: "Cancel",
        path: (item) => `/v1/leave-requests/${item.id}/cancel`,
        permission: "attendance.edit",
        confirm: "Cancel this leave request?",
        submitLabel: "Cancel",
        successMessage: "Leave request cancelled.",
      },
    ],
  },
  ...OPERATIONS_MODULES,
  ...ADMINISTRATION_MODULES,
  ...ACADEMICS_MODULES,
];

export function findModule(key: string): ModuleConfig | null {
  return MODULES.find((module) => module.key === key) ?? null;
}
