import type { ModuleConfig, SelectOption } from "./types";

export const SECTIONS = {
  overview: "Overview",
  academics: "Academics",
  account: "Account",
} as const;

const YEAR_STATUS: SelectOption[] = [
  { value: "draft", label: "Draft" },
  { value: "active", label: "Active" },
  { value: "closed", label: "Closed" },
];

const BOOL_STATUS: SelectOption[] = [
  { value: "1", label: "Active" },
  { value: "0", label: "Inactive" },
];

const SUBJECT_TYPE: SelectOption[] = [
  { value: "core", label: "Core" },
  { value: "elective", label: "Elective" },
  { value: "optional", label: "Optional" },
];

const ROOM_TYPE: SelectOption[] = [
  { value: "classroom", label: "Classroom" },
  { value: "lab", label: "Lab" },
  { value: "library", label: "Library" },
  { value: "hall", label: "Hall" },
  { value: "other", label: "Other" },
];

const ACADEMIC = {
  view: "academic.view",
  create: "academic.create",
  edit: "academic.edit",
  delete: "academic.delete",
};

const CURRICULUM = {
  view: "curriculum.view",
  create: "curriculum.create",
  edit: "curriculum.edit",
  delete: "curriculum.delete",
};

export const MODULES: ModuleConfig[] = [
  {
    key: "academic-years",
    section: SECTIONS.academics,
    label: "Academic years",
    endpoint: "/v1/academic-years",
    permissions: ACADEMIC,
    searchable: true,
    filters: [
      { param: "status", label: "Status", options: YEAR_STATUS },
      {
        param: "is_current",
        label: "Current",
        options: [
          { value: "1", label: "Current" },
          { value: "0", label: "Past" },
        ],
      },
    ],
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "starts_on", label: "Starts", format: "date" },
      { key: "ends_on", label: "Ends", format: "date" },
      { key: "status", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text" },
      { name: "starts_on", label: "Starts on", type: "date", required: true },
      { name: "ends_on", label: "Ends on", type: "date", required: true },
      { name: "status", label: "Status", type: "select", options: YEAR_STATUS },
      { name: "is_current", label: "Current year", type: "checkbox" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "terms",
    section: SECTIONS.academics,
    label: "Terms",
    endpoint: "/v1/terms",
    permissions: ACADEMIC,
    columns: [
      { key: "name", label: "Name" },
      { key: "academic_year.name", label: "Academic year" },
      { key: "starts_on", label: "Starts", format: "date" },
      { key: "ends_on", label: "Ends", format: "date" },
      { key: "is_current", label: "Current", format: "badge" },
    ],
    fields: [
      {
        name: "academic_year_id",
        label: "Academic year",
        type: "lookup",
        lookup: "academicYears",
        required: true,
        displayKey: "academic_year.name",
      },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "sequence", label: "Sequence", type: "number", min: 1 },
      { name: "starts_on", label: "Starts on", type: "date", required: true },
      { name: "ends_on", label: "Ends on", type: "date", required: true },
      { name: "is_current", label: "Current term", type: "checkbox" },
    ],
  },
  {
    key: "stages",
    section: SECTIONS.academics,
    label: "Stages",
    endpoint: "/v1/stages",
    permissions: ACADEMIC,
    searchable: true,
    filters: [{ param: "is_active", label: "Status", options: BOOL_STATUS }],
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "sequence", label: "Sequence" },
      { key: "is_active", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text" },
      { name: "sequence", label: "Sequence", type: "number", min: 1 },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "classes",
    section: SECTIONS.academics,
    label: "Classes",
    endpoint: "/v1/classes",
    permissions: ACADEMIC,
    searchable: true,
    filters: [{ param: "is_active", label: "Status", options: BOOL_STATUS }],
    columns: [
      { key: "name", label: "Name" },
      { key: "stage.name", label: "Stage" },
      { key: "capacity", label: "Capacity", align: "right" },
      { key: "is_active", label: "Status", format: "badge" },
    ],
    fields: [
      {
        name: "stage_id",
        label: "Stage",
        type: "lookup",
        lookup: "stages",
        required: true,
        displayKey: "stage.name",
      },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text" },
      { name: "sequence", label: "Sequence", type: "number", min: 1 },
      { name: "capacity", label: "Capacity", type: "number", min: 0 },
      { name: "room", label: "Room", type: "text" },
      {
        name: "in_charge_user_id",
        label: "In charge",
        type: "lookup",
        lookup: "staffUsers",
        displayKey: "in_charge.name",
      },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "sections",
    section: SECTIONS.academics,
    label: "Sections",
    endpoint: "/v1/sections",
    permissions: ACADEMIC,
    filters: [{ param: "is_active", label: "Status", options: BOOL_STATUS }],
    columns: [
      { key: "name", label: "Name" },
      { key: "class_room.name", label: "Class" },
      { key: "capacity", label: "Capacity", align: "right" },
      { key: "is_active", label: "Status", format: "badge" },
    ],
    fields: [
      {
        name: "class_room_id",
        label: "Class",
        type: "lookup",
        lookup: "classRooms",
        required: true,
        displayKey: "class_room.name",
      },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "capacity", label: "Capacity", type: "number", min: 0 },
      {
        name: "in_charge_user_id",
        label: "In charge",
        type: "lookup",
        lookup: "staffUsers",
        displayKey: "in_charge.name",
      },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "subjects",
    section: SECTIONS.academics,
    label: "Subjects",
    endpoint: "/v1/subjects",
    permissions: ACADEMIC,
    searchable: true,
    filters: [
      { param: "type", label: "Type", options: SUBJECT_TYPE },
      { param: "is_active", label: "Status", options: BOOL_STATUS },
    ],
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "type", label: "Type", format: "badge" },
      { key: "credit_hours", label: "Credits", align: "right" },
      { key: "is_active", label: "Status", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text" },
      { name: "type", label: "Type", type: "select", options: SUBJECT_TYPE },
      { name: "credit_hours", label: "Credit hours", type: "number", min: 0, step: 0.5 },
      { name: "weekly_periods", label: "Weekly periods", type: "number", min: 0 },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "periods",
    section: SECTIONS.academics,
    label: "Periods",
    endpoint: "/v1/periods",
    permissions: ACADEMIC,
    filters: [{ param: "is_active", label: "Status", options: BOOL_STATUS }],
    columns: [
      { key: "name", label: "Name" },
      { key: "sequence", label: "Sequence" },
      { key: "starts_at", label: "Starts" },
      { key: "ends_at", label: "Ends" },
      { key: "is_break", label: "Break", format: "badge" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "sequence", label: "Sequence", type: "number", min: 1, required: true },
      { name: "starts_at", label: "Starts at", type: "time", required: true },
      { name: "ends_at", label: "Ends at", type: "time", required: true },
      { name: "is_break", label: "Break period", type: "checkbox" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "rooms",
    section: SECTIONS.academics,
    label: "Rooms",
    endpoint: "/v1/rooms",
    permissions: ACADEMIC,
    searchable: true,
    filters: [
      { param: "type", label: "Type", options: ROOM_TYPE },
      { param: "is_active", label: "Status", options: BOOL_STATUS },
    ],
    columns: [
      { key: "name", label: "Name" },
      { key: "code", label: "Code" },
      { key: "block", label: "Block" },
      { key: "type", label: "Type", format: "badge" },
      { key: "capacity", label: "Capacity", align: "right" },
    ],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "code", label: "Code", type: "text" },
      { name: "block", label: "Block", type: "text" },
      { name: "floor", label: "Floor", type: "text" },
      { name: "type", label: "Type", type: "select", options: ROOM_TYPE },
      { name: "capacity", label: "Capacity", type: "number", min: 0 },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "class-subjects",
    section: SECTIONS.academics,
    label: "Class subjects",
    endpoint: "/v1/class-subjects",
    permissions: ACADEMIC,
    columns: [
      { key: "class_room.name", label: "Class" },
      { key: "subject.name", label: "Subject" },
      { key: "academic_year_id", label: "Academic year" },
      { key: "is_elective", label: "Elective", format: "badge" },
    ],
    fields: [
      {
        name: "academic_year_id",
        label: "Academic year",
        type: "lookup",
        lookup: "academicYears",
        required: true,
        displayKey: "academic_year.name",
      },
      {
        name: "class_room_id",
        label: "Class",
        type: "lookup",
        lookup: "classRooms",
        required: true,
        displayKey: "class_room.name",
      },
      {
        name: "subject_id",
        label: "Subject",
        type: "lookup",
        lookup: "subjects",
        required: true,
        displayKey: "subject.name",
      },
      { name: "weekly_periods", label: "Weekly periods", type: "number", min: 0 },
      { name: "is_elective", label: "Elective", type: "checkbox" },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "teaching-assignments",
    section: SECTIONS.academics,
    label: "Teaching assignments",
    endpoint: "/v1/teaching-assignments",
    permissions: ACADEMIC,
    columns: [
      { key: "teacher.name", label: "Teacher" },
      { key: "subject.name", label: "Subject" },
      { key: "class_room.name", label: "Class" },
      { key: "section.name", label: "Section" },
    ],
    fields: [
      {
        name: "academic_year_id",
        label: "Academic year",
        type: "lookup",
        lookup: "academicYears",
        required: true,
        displayKey: "academic_year.name",
      },
      {
        name: "teacher_user_id",
        label: "Teacher",
        type: "lookup",
        lookup: "staffUsers",
        required: true,
        displayKey: "teacher.name",
      },
      {
        name: "subject_id",
        label: "Subject",
        type: "lookup",
        lookup: "subjects",
        required: true,
        displayKey: "subject.name",
      },
      {
        name: "class_room_id",
        label: "Class",
        type: "lookup",
        lookup: "classRooms",
        required: true,
        displayKey: "class_room.name",
      },
      {
        name: "section_id",
        label: "Section",
        type: "lookup",
        lookup: "sections",
        dependsOn: "class_room_id",
        displayKey: "section.name",
      },
      { name: "weekly_periods", label: "Weekly periods", type: "number", min: 0 },
      { name: "is_active", label: "Active", type: "checkbox", defaultValue: true },
    ],
  },
  {
    key: "syllabus-units",
    section: SECTIONS.academics,
    label: "Syllabus units",
    endpoint: "/v1/syllabus-units",
    permissions: CURRICULUM,
    columns: [
      { key: "title", label: "Title" },
      { key: "subject.name", label: "Subject" },
      { key: "class_room.name", label: "Class" },
      { key: "sequence", label: "Sequence" },
    ],
    fields: [
      {
        name: "academic_year_id",
        label: "Academic year",
        type: "lookup",
        lookup: "academicYears",
        required: true,
        displayKey: "academic_year.name",
      },
      {
        name: "class_room_id",
        label: "Class",
        type: "lookup",
        lookup: "classRooms",
        required: true,
        displayKey: "class_room.name",
      },
      {
        name: "subject_id",
        label: "Subject",
        type: "lookup",
        lookup: "subjects",
        required: true,
        displayKey: "subject.name",
      },
      {
        name: "term_id",
        label: "Term",
        type: "lookup",
        lookup: "terms",
        displayKey: "term.name",
      },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "sequence", label: "Sequence", type: "number", min: 1 },
      { name: "estimated_periods", label: "Estimated periods", type: "number", min: 0 },
    ],
  },
  {
    key: "class-books",
    section: SECTIONS.academics,
    label: "Class books",
    endpoint: "/v1/class-books",
    permissions: CURRICULUM,
    columns: [
      { key: "title", label: "Title" },
      { key: "author", label: "Author" },
      { key: "class_room.name", label: "Class" },
      { key: "price", label: "Price", format: "money", align: "right" },
      { key: "is_required", label: "Required", format: "badge" },
    ],
    fields: [
      {
        name: "academic_year_id",
        label: "Academic year",
        type: "lookup",
        lookup: "academicYears",
        required: true,
        displayKey: "academic_year.name",
      },
      {
        name: "class_room_id",
        label: "Class",
        type: "lookup",
        lookup: "classRooms",
        required: true,
        displayKey: "class_room.name",
      },
      {
        name: "subject_id",
        label: "Subject",
        type: "lookup",
        lookup: "subjects",
        displayKey: "subject.name",
      },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "author", label: "Author", type: "text" },
      { name: "publisher", label: "Publisher", type: "text" },
      { name: "isbn", label: "ISBN", type: "text" },
      { name: "edition", label: "Edition", type: "text" },
      { name: "price", label: "Price", type: "number", min: 0, step: 0.01 },
      { name: "is_required", label: "Required", type: "checkbox" },
    ],
  },
];

export function findModule(key: string): ModuleConfig | null {
  return MODULES.find((module) => module.key === key) ?? null;
}
