// AUTO-GENERATED by scripts/build-locales.mjs -- do not edit by hand.
// Run: pnpm --filter @eis/i18n gen
import { en } from "./en";
import ur from "./ur.json";
import type { LocaleMeta, Messages } from "../types";

function stripMeta(catalog: { $meta?: unknown }): Partial<Messages> {
  const { $meta, ...messages } = catalog;
  return messages as Partial<Messages>;
}

export const LOCALES: LocaleMeta[] = [
  { code: "en", name: "English", nativeName: "English", dir: "ltr" },
  { code: "ur", ...(ur.$meta as Omit<LocaleMeta, "code">) },
];

export const MESSAGES: Record<string, Partial<Messages>> = {
  en,
  "ur": stripMeta(ur),
};

export type MessageKey =
  | "app.name"
  | "app.loading"
  | "app.settings"
  | "common.done"
  | "common.cancel"
  | "common.save"
  | "common.saving"
  | "common.delete"
  | "common.edit"
  | "common.create"
  | "common.add"
  | "common.new"
  | "common.search"
  | "common.loading"
  | "common.retry"
  | "common.close"
  | "common.back"
  | "common.yes"
  | "common.no"
  | "common.ok"
  | "common.confirm"
  | "common.remove"
  | "common.actions"
  | "common.status"
  | "common.all"
  | "common.none"
  | "common.optional"
  | "common.total"
  | "common.view"
  | "common.required"
  | "common.error"
  | "common.signOut"
  | "common.of"
  | "errors.generic"
  | "errors.network"
  | "errors.required"
  | "errors.unauthorized"
  | "auth.brand"
  | "auth.tagline"
  | "auth.email"
  | "auth.emailPlaceholder"
  | "auth.password"
  | "auth.passwordPlaceholder"
  | "auth.signIn"
  | "auth.signingIn"
  | "auth.missingCredentials"
  | "auth.failed"
  | "auth.appearance"
  | "navigation.dashboard"
  | "navigation.profile"
  | "navigation.timetable"
  | "navigation.attendance"
  | "navigation.results"
  | "navigation.fees"
  | "navigation.students"
  | "appearance.title"
  | "appearance.colorMode"
  | "appearance.mode.system"
  | "appearance.mode.light"
  | "appearance.mode.dark"
  | "appearance.accentColor"
  | "appearance.vibrantPalette"
  | "appearance.vibrantPaletteHint"
  | "appearance.background"
  | "appearance.family.default"
  | "appearance.family.solid"
  | "appearance.family.gradient"
  | "appearance.family.wallpaper"
  | "appearance.defaultSurface"
  | "appearance.dimming"
  | "appearance.decreaseDimming"
  | "appearance.increaseDimming"
  | "appearance.surface"
  | "appearance.glassSurfaces"
  | "appearance.glassSurfacesHint"
  | "appearance.glassBlur"
  | "appearance.glassBlurHint"
  | "appearance.transparency"
  | "appearance.transparencyHint"
  | "appearance.backgroundBlur"
  | "appearance.backgroundBlurHint"
  | "appearance.presetHint"
  | "appearance.recommended"
  | "appearance.recommendedA11y"
  | "appearance.interfaceAnimations"
  | "appearance.interfaceAnimationsHint"
  | "appearance.reset"
  | "appearance.decreaseLabel"
  | "appearance.increaseLabel"
  | "appearance.language"
  | "appearance.languageHint";
