import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  baseKeyOf,
  codeFromFile,
  identifier,
  listJsonCatalogs,
  localesDir,
  readEnglish,
  validate,
} from "./catalog.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const dir = localesDir(root);

const english = readEnglish(dir);
const englishKeys = Object.keys(english);

const catalogs = listJsonCatalogs(dir).map((file) => {
  const code = codeFromFile(file);
  const raw = JSON.parse(fs.readFileSync(path.join(dir, file), "utf8"));
  const { $meta, ...messages } = raw;
  return { code, file, meta: $meta, messages };
});

const { errors, warnings, missingByLocale } = validate(english, catalogs);

if (warnings.length) {
  for (const warning of warnings) console.warn(`warn: ${warning}`);
}

if (errors.length) {
  for (const error of errors) console.error(`error: ${error}`);
  console.error(`\n${errors.length} catalog error(s); registry not written.`);
  process.exit(1);
}

const messageKeys = [];
const seen = new Set();
for (const key of englishKeys) {
  const base = baseKeyOf(key);
  if (!seen.has(base)) {
    seen.add(base);
    messageKeys.push(base);
  }
}

const imports = catalogs
  .map(({ code, file }) => `import ${identifier(code)} from "./${file}";`)
  .join("\n");

const englishMeta = `{ code: "en", name: "English", nativeName: "English", dir: "ltr" }`;

const localeEntries = catalogs
  .map(
    ({ code, meta }) =>
      `  { code: ${JSON.stringify(code)}, ...(${identifier(code)}.$meta as Omit<LocaleMeta, "code">) },`
  )
  .join("\n");

const messageEntries = catalogs
  .map(({ code }) => `  ${JSON.stringify(code)}: stripMeta(${identifier(code)}),`)
  .join("\n");

const keyUnion = messageKeys.map((key) => `  | ${JSON.stringify(key)}`).join("\n");

const output = `// AUTO-GENERATED by scripts/build-locales.mjs -- do not edit by hand.
// Run: pnpm --filter @eis/i18n gen
import { en } from "./en";
${imports}
import type { LocaleMeta, Messages } from "../types";

function stripMeta(catalog: { $meta?: unknown }): Partial<Messages> {
  const { $meta, ...messages } = catalog;
  return messages as Partial<Messages>;
}

export const LOCALES: LocaleMeta[] = [
  ${englishMeta},
${localeEntries}
];

export const MESSAGES: Record<string, Partial<Messages>> = {
  en,
${messageEntries}
};

export type MessageKey =
${keyUnion};
`;

fs.writeFileSync(path.join(dir, "index.ts"), output);

const total = messageKeys.length;
console.log(
  `@eis/i18n: wrote locales/index.ts (${catalogs.length + 1} locales, ${total} keys).`
);
for (const { code } of catalogs) {
  const missing = missingByLocale[code]?.length ?? 0;
  if (missing) {
    console.log(`  ${code}: ${missing} missing key(s) fall back to English`);
  }
}
